---
title: "Blowup of a relative ideal"
format: html
engine: markdown
---

## thatDefinition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $E$ be a [relative ideal](Relative-ideal.qmd) of $S$ with [multiplicity ideal](Multiplicity-ideal.qmd) $m(E)$ and [reduction number](Reduction-number.qmd) $r(E)$. It is defined the blowup of $E$, also known as Lipman semigroup of $S$, denoted by $\mathcal{B}(E)$, as the relative ideal $\mathcal{B}(E) = r(E)E - r(E)m(E)$, where $nE = \{e_1 + e_2 + \cdots + e_n ~ | ~ e_1, \ldots, e_n \in E\}$ for all $n \in \mathbb{N} \setminus \{0\}$ and $A - B = \{z \in \mathbb{Z} ~ | ~ z + B \subseteq A\}$ for $A,B \subseteq \mathbb{Z}$.

It can be proven that $\mathcal{B}(E)$ is a numerical semigroup and the equality $\mathcal{B}(E) = r(E)E - r(E)E$ holds.

## Examples

$\circ$ Let $S = \langle 5, 9, 12, 13 \rangle$, $I = \{14, 17\}$ and $E = I + S = \{14, 17, 19, 22, 23, 24, 26, \rightarrow \}$. We have $m(E) = 14$, and for $h = 1$,

$$
E + E = \{28, 31, 33, 34, 36, \rightarrow\} \ne \{28, 31, 33, 36, 37, 38, 40, \rightarrow \} = 14 + E.
$$

For $h = 2$,

$$
3E = (E + E) + E = \{42, 45, 47, 48, 50 , \rightarrow\} = 12 + 2E.
$$

Therefore, $r(E) = 2$ and the blowup of $E$ is $\mathcal{B}(E) = 2E - 2E = \{0, 3, 5, 6, 8, \rightarrow\}$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 16, 21, 30, 47 \rangle$, $I = \{37, 51, 102\}$ and $IS = I + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(16, 21, 30, 47);
<Numerical semigroup with 4 generators>
gap> I := [37, 51, 102];
[ 37, 51, 102 ]
gap> IS := I + S;
<Ideal of numerical semigroup>
```

The functions `BlowUp` and `BlowUpIdealOfNumericalSemigroup` return the blowup of a given relative ideal.

``` gap
gap> L := BlowUp(IS);
<Ideal of numerical semigroup>
gap> BlowUp(IS) = BlowUpIdealOfNumericalSemigroup(IS);
true
gap> Generators(L);
[ 0, 14, 28 ]
```

Given a relative ideal $L$, the function `MinimalGenerators` returns a list $J$ such that $L = J + S$. The function `ReductionNumber` returns the reduction number of a given relative ideal.

```         
gap> r := ReductionNumber(IS);
2
gap> L = r*IS - r*IS;
true
```

$\diamond$ Given a numerical semigroup, the functions `BlowUp` and `BlowUpOfNumericalSemigroup` returns the blowup of the [maximal ideal](Maximal-ideal.qmd) of $S$, that is, $M = S\setminus \{0\}$.

``` gap
gap> S := NumericalSemigroup(33, 41, 46, 70, 83);
<Numerical semigroup with 5 generators>
gap> BM := BlowUp(S);
<Numerical semigroup with 5 generators>
gap> BlowUp(S) = BlowUpOfNumericalSemigroup(S);
true
gap> Generators(BM);
[ 8, 13, 33, 37, 50 ]
```

Since the blowup of a relative ideal is a numerical semigroup, this process can be repeated. From this, process, it is defined the [multiplicity sequence](Multiplicity-sequence.qmd) of $S$.

## References
