---
title: "Conductor ideal"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is defined the conductor ideal of $S$ as the set $S - \mathbb{N} = \{z \in \mathbb{Z} ~ | ~ z + \mathbb{N} \subseteq S \}$. Equivalently, the conductor ideal of $S$ is defined as the numerical semigroup $S - \mathbb{N} = \{C(S), \rightarrow \}$, where $C(S)$ denotes the [conductor](../Basic-concepts/Conductor.qmd) of $S$.

## Examples

$\circ$ Let $S = \langle 5, 8, 11 \rangle$. Computing the first elements of $S$, it is obtained that $S = \{0, 5, 8, 10, 11, 13, 15, 16, 18, \rightarrow \}$, thus $C(S) = 18$ and $S - \mathbb{N} = \{18, \rightarrow \}$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 15, 20 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 15, 20);
<Numerical semigroup with 3 generators>
```

Given a numerical semigroup, the function `Conductor` returns the conductor of the numerical semigroup.

``` gap
gap> C = Conductor(S);
78
```

Then, the conductor ideal of $S$ is $S - \mathbb{N} = \{78, \rightarrow\}$. The minimal system of generators of the conductor ideal is $I = \{C(S), C(S) + 1, \ldots, C(S) + m(S)\}$, where $m(S)$ denotes the [multiplicity](../Basic-concepts/Multiplicity.qmd) of $S$. The function `Multiplicity` computes the multiplicity of a given numerical semigroup.

``` gap
gap> M := Multiplicity(S);
13
gap> IS := [C..C+M] + S;
<Ideal of numerical semigroup>
```

$\diamond$ Given a relative ideal $IS$ of $S$, it can be defined the conductor of $IS$ as the least element $x \in IS$ such that $s + \mathbb{N} \subseteq IS$. This element exists since $IS + S \subseteq IS$. The functions `Conductor` and `ConductorOfIdealOfNumericalSemigroup` compute the conductor of a given relative ideal.

``` gap
gap> S := NumericalSemigroup(33, 49, 76, 133);
<Numerical semigroup with 4 generators>
gap> IS := [-13, -5, 6, 21] + S;
<Ideal of numerical semigroup>
gap> Conductor(IS);
232
```

## References
