---
title: "Genus of a relative ideal"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $E$ be a [relative ideal](Relative-ideal.qmd) of $S$. It is defined the genus of $E$ as $g(E) = |(m(E) + \mathbb{N}) \setminus E|$, where $m(E)$ denotes the [multiplicity](Multiplicity-ideal.qmd) of $E$.

## Examples

$\circ$ Let $S = \langle 5, 7, 9 \rangle = \{0, 5, 7, 9, 10, 12, 14, \rightarrow \}$ and $E = \{-14\} + S = \{-14, -9, -7, -5, -4, -2, 0, \rightarrow\}$. Clearly, $m(E) = -14$, so $g(E) = |(-14 + \mathbb{N}) \setminus E| = |\{-13, -12, -11, -10, -8, -6, -3, -1\}| = 8$.

$\circ$ The definition of genus of a relative ideal is a generalization of the definition of [genus](../Basic-concepts/Genus.qmd) of a numerical semigroup. Indeed, let $S$ be a numerical semigroup with genus $g$. In particular, $S$ is a relative ideal of itself, then $g(S) = |(m(S) + \mathbb{N}) \setminus S|$. The multiplicity of $S$ (as relative ideal) is $m(S) = 0$, therefore $g(S) = |\mathbb{N} \setminus S| = g$.

## Examples with GAP

Nowadays, there are no functions in package NumericalSgps related to genus of a relative ideal. However, given a relative ideal $E$, the following function returns the genus of $E$.

``` gap
gap> GenusOfRelativeIdeal := function(I)
>       local m, T;
>       if not IsIdealOfNumericalSemigroup(I) then
>               Error("The argument must be a relative ideal");
>       fi;
>       m := Minimum(I);
>       T := m + NumericalSemigroup(1);
>       return Length(Difference(T, I));
> end;
```

$\diamond$ Let $S = \langle 33, 37, 41, 45, 91 \rangle$ and $I = \{-14, -11, -3, 5, 12 \} + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(33, 37, 41, 45, 91);
<Numerical semigroup with 5 generators>
gap> I := [-14, -11, -3, 5, 12] + S;
<Ideal of numerical semigroup>
```

Applying the function defined above, the genus of the relative ideal $I$ is

``` gap
gap> GenusOfRelativeIdeal(I);
62
```

From the definition, it can be deduced that $g(I) = C(I) - m(I) + 1 - |N(I)|$, where $C(I)$ is the conductor of $I$, defined in the same way as the [conductor](../Basic-concepts/Conductor.qmd) of a numerical semigroup, and $N(I)$ is the set of left elements of $I$, again defined in the same way as the [left elements](../Basic-concepts/Left-elements.qmd) of a numerical semigroup.

``` gap
gap> Conductor(I) - Minimum(I) + 1 - Length(SmallElements(I));
62
```

## References
