---
title: "Integrally closed ideal"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $E$ be a [proper ideal](Proper-ideal.qmd) of $S$. It is said that $E$ is integrally closed if it is of the form $S(s) = (s + \mathbb{N}) \cap S$ for some $s \in S$.

It can be proven that $E$ is integrally closed if, and only if, $E = S(m(E))$, where $m(E)$ denotes the [multiplicity ideal](Multiplicity-ideal.qmd) of $E$. On the other hand, a numerical semigroup $S$ is an [Arf semigroup](../Families-NS/Arf-semigroup.qmd) if, and only if, every integrally closed ideal is [stable](Stable-ideal.qmd).

## Examples

$\circ$ Let $S$ a numerical semigroup, then the [maximal ideal](Maximal-ideal.qmd) $M = S^*$ is integrally closed, since $S^* = (m(S) + \mathbb{N}) \cap S$, where $m(S)$ denotes the [multiplicity](../Basic-concepts/Multiplicity.qmd) of $S$ as a numerical semigroup.

$\circ$ Let $S = \langle 5, 7, 9 \rangle = \{0, 5, 7, 9, 10, 12, 14, \rightarrow \}$, $I = \{9, 10, 12, 14\}$ and $E = I + S$, let us prove the equality $E = (9 + \mathbb{N}) \cap S$. First, $(9 + \mathbb{N}) \cap S = \{9, 10, 12, 14, \rightarrow\}$, then we have to prove that $E = \{9, 10, 12, 14, \rightarrow\}$.

-   Let $e \in E$, then there exists $i \in I$ and $s \in S$ such that $e = i + s$. If $s = 0$, $e \in I \subseteq \{9, 10, 12, 14, \rightarrow\}$, otherwise, $e = i + s \ge i + 5 \ge 14$ and $e \in \{9, 10, 12, 14, \rightarrow\}$.

-   From the fact that $\{14, 15, 16, 17, 18\} \subseteq E$, it is deduced that for all $n \ge 14$ it holds $n \in E$ and $\{9, 10, 12, 14, \rightarrow\} \subseteq E$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 15, 29, 31 \rangle$, $I = \{72, 75, 77\}$ and $IS = I + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 15, 29, 31);
<Numerical semigroup with 4 generators>
gap> I := [42, 43, 44, 45, 46, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 65, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 83, 93];
[ 42, 43, 44, 45, 46, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 65, 67, 68,
  69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 83, 93 ]
gap> IS := I + S;
<Ideal of numerical semigroup>
```

There is no direct function that determines whether a proper ideal is integrally closed or not, but it is easy to compute it from the fact that $IS$ is integrally closed if, and only if, $IS = (m(IS) + \mathbb{N}) \cap S$.

``` gap
gap> m := Minimum(IS);
73
gap> N1 := NumericalSemigroupBySmallElements([0, m]);
<Numerical semigroup>
gap> L := MaximalIdeal(Intersection(N1,S));
<Ideal of numerical semigroup>
gap> IsSubset(IS, L) = IsSubset(L, IS);
true
```

First, the function `Minimum` returns the multiplicity of a proper ideal, $m(IS)$; afterwards, the function `NumericalSemigroupBySmallElements` generates the numerical semigroup given a list, considered as the list of left elements along with the conductor of a numerical semigroup. Then, $N1 = \{0, m(IS), \rightarrow\} = (m(IS) + \mathbb{N})\cup\{0\}$; also, the function `Intersection` computes the intersection of two given numerical semigroups. Therefore, $N1 \cap S = ((m(IS) + \mathbb{N}) \cap S) \cup \{0\}$; then, the function `MaximalIdeal` returns the maximal ideal of the numerical semigroup, $L = (m(IS) + \mathbb{N}) \cap S$; finally, given two subsets $I,J$ of $\mathbb{N}$, the function `IsSubset` returns true if $J \subseteq I$. To sum up, $IS = (73 + \mathbb{N}) \cap S$ and $IS$ is an integrally closed ideal.

## References

::: {#refs}

:::
