---
title: "Maximal ideal"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is defined the maximal ideal of $S$ as the subset $M = S^*$, and it is denoted by $M(S)$. This definition is motivated by the definitions of [relative ideal](Relative-ideal.qmd) of $S$ and [proper ideal](Proper-ideal.qmd) of $S$.

## Examples

$\circ$ Let $S$ a numerical semigroup and $E$ a proper ideal of $S$. By definition, $E \subseteq S$, and if $0 \in E$, then $S \subseteq S + E$. On the other hand, by definition of proper ideal, $S + E \subseteq E$, concluding that $E = S$. In conclusion, every proper ideal of $S$ other than $S$ is a subset of $S^*$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 15, 20 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 15, 20);
<Numerical semigroup with 3 generators>
```

There are two ways to compute the maximal ideal of a numerical semigroup, these are with the functions `MaximalIdeal` and `MaximalIdealOfNumericalSemigroup`.

``` gap
gap> I := MaximalIdeal(S);
<Ideal of numerical semigroup>
gap> J := MaximalIdealOfNumericalSemigroup(S);
<Ideal of numerical semigroup>
gap> I = J;
true
```

## References
