---
title: "Maximum sparse ideal"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) with [genus](../Basic-concepts/Genus.qmd) $g(S)$ and [Frobenius number](../Basic-concepts/Frobenius-number.qmd) $F(S)$, and let $E$ be a [proper ideal](Proper-ideal.qmd) of $S$ with [Frobenius number ideal](Frobenius-number-ideal.qmd) $F(E)$. It is said that $E$ is a maximum sparse ideal if it satisfies the equality $F(E) = 2g(S) - 1 + |S \setminus E|$.

If the [multiplicity of a relative ideal](Multiplicity-ideal.qmd) is denoted by $m(E)$ and the [genus of a relative ideal](Genus-ideal.qmd) by $g(E)$, it can be proven that the equality is equivalent to $F(S) + 1 - g(S) = g(\tilde{E}) + m(\tilde{E})$, where $\tilde{E} = E + F(S) - F(E)$.

## Examples

$\circ$ Let $S = \langle 4, 9 \rangle$ and the proper ideal $E = \{F(S) + 1, \rightarrow \}$ (in fact, is the [conductor ideal](Conductor-ideal.qmd) of $S$). In this case, $E = \tilde{E}$, and it holds $F(S) = 11, ~ g(S) = 6, ~ g(E) = 0$ and $m(E) = F(S) + 1$. Then, $F(S) + 1 - g(S) = 6 < 12 = m(\tilde{E}) + g(\tilde{E})$. Hence, $E$ is not a maximum sparse ideal.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 32, 79, 81, 101 \rangle$ and $IS = \{26, 45, 58, 94, 111\} + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 32, 79, 81, 101);
<Numerical semigroup with 5 generators>
gap> IS := [26, 45, 58, 94, 111] + S;
<Ideal of numerical semigroup>
```

It can be proven that a proper ideal $E$ is a maximum sparse ideal if, and only if, $\tilde{E} = K(S)$, where $K(S)$ is the [standard canonical ideal](Standard-canonical-ideal.qmd) of $S$. Therefore, if $E$ is a maximum sparse ideal, then is a [canonical ideal](Canonical-ideal.qmd) of $S$ such that $E \subseteq S$. Given a [relative ideal](Relative-ideal.qmd) $IS$, the function `IsCanonicalIdeal` returns true or false depending on whether $IS$ is a canonical ideal or not.

``` gap
gap> IsSubset(0+S, IS);
true
gap> IsCanonicalIdeal(IS);
false
```

To sum up, $IS$ is not a maximum sparse ideal.

## References

::: {#refs}

:::
