---
title: "Proper ideal"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $E$ be a subset of $\mathbb{Z}$. It is said that $E$ is a proper ideal, an integral ideal, or simply an ideal of $S$, if $E$ is a [relative ideal](Relative-ideal.qmd) of $S$ and $E \subseteq S$.

## Examples

$\circ$ Let's prove that $E = S^*$ is an ideal of $S$. Clearly $S^* \subseteq S$ and $S + S^* \subseteq S^*$. If we consider $s = C(S)$, where $C(S)$ denotes the [conductor](../Basic-concepts/Conductor.qmd) of $S$, it is deduced that $C(S) + S^* \subseteq S$ and $S^*$ is an ideal. The ideal $S^*$ is called the [maximal ideal](Maximal-ideal.qmd) of $S$.

$\circ$ Let $b \in \mathbb{N}$ an odd natural arbitrary but fixed, $S = \langle 2, b \rangle = \{0, 2, 4, \ldots, b - 1, \rightarrow\}$ and $E = \{0, b, \rightarrow \}$. Clearly, $E$ is an ideal of $S$. In general, given a numerical semigroup $S$, the set $E = \{C(S), \rightarrow\}$ is a proper ideal and is called the [conductor ideal](Conductor-ideal.qmd) of $S$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 10, 11, 15, 19 \rangle$, $I = \{20, 21, 25\}$ and the relative ideal $IS = I + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(10, 11, 15, 19);
<Numerical semigroup with 4 generators>
gap> I := [20, 21, 25];
[ 20, 21, 25 ]
gap> IS := I + S;
<Ideal of numerical semigroup>
```

The functions `IsIntegral` and `IsIntegralIdealOfNumericalSemigroup` return true or false depending on whether an ideal of a semigroup is contained in the semigroup or not.

``` gap
gap> IsIntegral(IS);
true
gap> IsIntegral(IS) = IsIntegralIdealOfNumericalSemigroup(IS);
true
```

$\diamond$ Given $IS, JS$ ideals of a numerical semigroup $S$ with $JS \subseteq IS$, the functions `Difference` and `DifferenceOfIdealsOfNumericalSemigroup` return the set $I \setminus J$.

``` gap
gap> IsSubset(IS, JS);
true
gap> IS := [-4, 7, 22, 35, 64] + S;
<Ideal of numerical semigroup>
gap> JS := [-4, 21, 28, 43, 50, 51] + S;
<Ideal of numerical semigroup>
gap> Difference(IS, JS);
[ 7, 14, 22, 29, 36, 44 ]
```

Given a numerical semigroup $S$ and a subset $X$ of $S$, the function `IsComplementOfIntegralIdeal` returns true or false depending on whether $X$ is a complement of a proper ideal or not.

``` gap
gap> IsComplementOfIntegralIdeal([0, 36, 46, 50, 51],S);
false
gap> IsComplementOfIntegralIdeal([0, 46, 83],S);
true
```

## References

::: {#refs}

:::
