---
title: "Ratliff-Rush number of a proper ideal"
format: html
engine: markdown
---

<!-- [DGH01] D'Anna, M., Guerrieri, A. and Heinzer, W., Invariants of ideals having principal reductions, Comm. Algebra, 29 (2) (2001), 889--906. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $E$ a [proper ideal](Proper-ideal.qmd) of $S$. It is defined the Ratliff-Rush number of $I$, denoted by $R(I)$, as the least integer $n$ such that $S \cap ( (n+1)I - nI)$ is the [Ratliff-Rush closure](Ratliff-Rush-closure.qmd) of $I$.

If $r(I)$, that is, the minimum $h \ge 1$ such that $(h + 1)I = m(I) + hI$, where $m(I)$ is the [multiplicity](Multiplicity-ideal.qmd) of $I$, it can be proven that $R(I) \le r(I)$.

## Examples

$\circ$ Let $S = \langle 3, 5, 7 \rangle$ and $I = \{2, 4\} + S = \{2, 4, 5, 7, \rightarrow \}$. Clearly, $m(I) = 2$, then we are looking for the smaller $h \in \mathbb{N} \setminus \{0\}$ such that $(h+1)I = 2 + hI$. If we take $h = 1$,

$$
2I = I + I = \{4, 6, \rightarrow\} \ne \{4, 6, 7, 9, \rightarrow \} = 2 + I.
$$

For $h = 2$,

$$
3I = (I + I) + I = \{6, 8, \rightarrow\} = 2 + 2I
$$

Then, the reduction number of $I$ is $r(I) = 2$. Now, with few computations,

$$
S \cap (2I - I) = \{5, \rightarrow \} = S \cap (3I - 2I),
$$

concluding that the Ratliff-Rush number of $I$ is $R(I) = 1$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 50, 54, 78, 115, 116, 119 \rangle$ and $I = \{50, 78, 119\} + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(50, 54, 78, 115, 116, 119);
<Numerical semigroup with 6 generators>
gap> I := [50, 78, 119] + S;
<Ideal of numerical semigroup>
```

Given a relative ideal $I$ of a numerical semigroup, the functions `RatliffRushNumber` and `RatliffRushNumberOfIdealOfNumericalSemigroup` return the Ratliff-Rush number of $I$.

``` gap
gap> RatliffRushNumber(I);
6
gap> RatliffRushNumberOfIdealOfNumericalSemigroup(I) = RatliffRushNumber(I);
true
```

Then, the Ratliff-Rush closure of $I$ is $S \cap (7I - 6I)$.


$\diamond$ Let $S = \langle 39, 96, 105, 120, 130 \rangle$ and $I = \{96, 169, 183, 195 \} + S$, in GAP:


```gap
gap> S := NumericalSemigroup(39, 96, 105, 120, 130);
<Numerical semigroup with 5 generators>
gap> I := [96, 169, 183, 195] + S;
<Ideal of numerical semigroup>
```

Given a proper ideal $I$, the functions `AsymptoticRatliffRushNumber` and `AsymptoticRatliffRushNumberOfIdealOfNumericalSemigroup` return the least integer $n$ such that the Ratliff-Rush closure of 
$mI$ equals to $mI$ for all $m \ge n$, that is, the asymptotic Ratliff-Rush number.


```gap
gap> AsymptoticRatliffRushNumber(I);
4
gap> RatliffRushNumber(I);
3
```

It can be proven that the asymptotic Ratliff-Rush number is greater or equal to the Ratliff-Rush number.


## References
