---
title: "Set closed under divisors"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd), $\le_S$ the [relation order of S](../Basic-concepts/Relation-order-NS.qmd) and $X$ a subset of $\mathbb{N}$. It is said that $X$ is closed under divisors if for all $x \in X$ and $y \in S$ such that $y \le_S x$, it holds $y \in X$.

Let $X$ a subset of $\mathbb{N}$. It can be proven that $X$ is a set closed under divisors if, and only if, $E = S \setminus X$ is a [proper ideal](Proper-ideal.qmd) of $S$.

## Examples

$\circ$ Let us prove that if $E$ is a proper ideal of $S$, then its complement $X = S \setminus E$ is closed under divisors. Let $x \in X$ and $y \in S$ such that $y \le_S x$. Therefore, there exists $s \in S$ so that $x = y + s$. If we suppose $y \not \in X$, then $y \in E$ and $x = s + y \in S + E \subseteq E$, which is a contradiction. In conclusion, $y \in X$ and $X$ is closed under divisors.

$\circ$ Let $S = \langle 5, 11, 14 \rangle = \{0, 5, 10, 11, 14, 15, 16, 19, 20, 21, 22, 24 , \rightarrow\}$ and $E = \{5, 14\} + S \subseteq S$. We have that

$$
E = I + S = \{5, 10, 14, 15, 16, 19, 20, 21, 24 , \rightarrow\},
$$

and $X = S \setminus E = \{0, 11, 22\}$ is a set closed under divisors.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 10, 11, 15, 19 \rangle$, $I = \{20, 21, 25\}$ and the proper ideal $IS = I + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(10, 11, 15, 19);
<Numerical semigroup with 4 generators>
gap> I := [20, 21, 25];
[ 20, 21, 25 ]
gap> IS := I + S;
<Ideal of numerical semigroup>
```

Given a subset $X$ of $\mathbb{N}$ and a numerical semigroup $S$, the function `IsComplementOfIntegralIdeal` returns true or false depending on whether $X$ is a set closed under divisors or not. The function `Difference` gets two proper ideals $I, J$ of the same numerical semigroup with $J \subseteq I$, and returns $I \setminus J$.

``` gap
gap> d := Difference(0 + S, IS);
[ 0, 10, 11, 15, 19, 22, 26, 29, 33, 34, 37, 38, 48 ]
gap> IsComplementOfIntegralIdeal(d, S);
true
```

Given a set $X$ closed under divisor, the function `IdealByDivisorClosedSet` returns the proper ideal $S \setminus X$.

``` gap
gap> IS = IdealByDivisorClosedSet(d,S);
true
```

## References
