---
title: "Standard canonical ideal"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $F(S)$ the [Frobenius number](../Basic-concepts/Frobenius-number.qmd) of $S$. The standard canonical ideal of $S$ is defined as

$$
K(S) = \{x \in \mathbb{Z} ~ | ~ F(S) - x \not \in S\}.
$$

It can be proven that the standard canonical ideal is a [relative ideal](Relative-ideal.qmd) of $S$ and $S \subseteq K(S) \subseteq \mathbb{N}$.

## Examples

$\circ$ Let $S = \langle 4, 9, 10 \rangle = \{0, 4, 8, 9, 10, 12, 13, 14, 16, \rightarrow \}$. The Frobenius number of $S$ is $F(S) = 15$, thus $K(S) = \{x \in \mathbb{Z} ~ | ~ 15 - x \not \in S\}$. The set of [gaps](../Basic-concepts/Gap.qmd) of $S$ is $G(S) = \{1, 2, 3, 5, 6, 7, 11, 15\}$, then if we compute $15 -g$ for every $g \in G(S)$, we have that $K(S) = S \cup \{4, 8, 9, 10, 12, 13, 14\} = S$. It can be proven that $S = K(S)$ if, and only if, $S$ is [symmetric](../Families-NS/NS-symmetric.qmd).

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 5, 7, 13, 16 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(5, 7, 13, 16);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup, the functions `CanonicalIdeal` and `CanonicalIdealOfNumericalSemigroup` return the standard canonical ideal of the numerical semigroup.

``` gap
gap> K := CanonicalIdeal(S);
<Ideal of numerical semigroup>
gap> CanonicalIdeal(S) = CanonicalIdealOfNumericalSemigroup(S);
true
```

On the other hand, given a relative ideal $E$ of a numerical semigroup $S$, the functions `IsCanonicalIdeal` and `IsCanonicalIdealOfNumericalSemigroup` return true or false depending on whether the relative ideal $E$ is a translation of the canonical ideal, that is, if there exists $x \in \mathbb{Z}$ such that $E = x + K(S)$. In this case, it is said that $E$ is a [canonical ideal](Canonical-ideal.qmd) of $S$.

``` gap
gap> IsCanonicalIdeal(K);
true
gap> K2 := 3 + K;
<Ideal of numerical semigroup>
gap> IsCanonicalIdeal(K2);
true
gap> IsCanonicalIdeal(K2) = IsCanonicalIdealOfNumericalSemigroup(K2);
true
```

## References
