---
title: "Translation of a relative ideal"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $I,J$ be [relative ideals](Relative-ideal.qmd) of $S$, with $J$ [minimally generated](Minimal-set-generators-ideal.qmd) by $\{j_1, \ldots, j_n\}$. It is said that $I$ is a translation of $J$ if there exists $k \in \mathbb{Z}$ such that $I$ is generated by $\{j_1 + k, \ldots, j_n + k\}$. In this case, it is said that $I$ and $J$ are equivalents.

## Examples

$\circ$ If $J$ is a relative ideal of a numerical semigroup $I$ minimally generated by $\{j_1, \ldots, j_n\}$, then for any $k \in \mathbb{Z}$, the translation of $J$ by $k$ is minimally generated by $\{j_1 + k, \ldots, j_n + k\}$. Indeed, if $I$ is a translation of $J$ by $k$, Then its set of minimal generators is $I \setminus (I + M)$ and $j + k \in I \setminus (M + I)$ if, and only if, $j \in J \setminus (M + J)$, concluding that $j_i + k$ is minimal and $\{j_1+k, \ldots, j_n + k\}$ is the set of minimal generators of $I$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 25, 26, 33, 65, 80, 81 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(25, 26, 33, 65, 80, 81);
<Numerical semigroup with 6 generators>
gap> I := [8, 17, 38, 45, 65] + S;
<Ideal of numerical semigroup>
```

Given a relative ideal of a numerical semigroup and an integer $k$, the function `TranslationOfIdealOfNumericalSemigroup` returns the translation of $I$ by $k$.

``` gap
gap> J := TranslationOfIdealOfNumericalSemigroup(15, I);
<Ideal of numerical semigroup>
```

The translation can be also computed with the $+$ operator.

``` gap
gap> J = I + 15;
true
```

## References

::: {#refs}

:::