---
title: "Type of a relative ideal"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and let $E$ be a [relative ideal](Relative-ideal.qmd) of $S$. It is defined the type of $E$ as $t(E) = |(E - M) \setminus E|$, where $M = S^*$ is the [maximal ideal](Maximal-ideal) of $S$ and

$$
E - M = \{z \in \mathbb{Z} ~ | ~ z + M \subseteq E\}.
$$

## Examples

$\circ$ The definition of type of a relative ideal is a generalization of the definition of [type](../Basic-concepts/Type.qmd) of a numerical semigroup. Indeed, let $S$ be a numerical semigroup with type $t$. In particular, $S$ is a relative ideal of itself, then $t(S) = |(S - S^*) \setminus S|$. By definition,

$$
S - S^* = \{z \in \mathbb{Z} ~ | ~ z + S^* \subseteq S\},
$$

where it is deduced that $(S - S^*) \setminus S$ is the set of [pseudo-Frobenius number](../Basic-concepts/Pseudo-Frobenius-number.qmd) of $S$. In conclusion, $t(S) = t$.

$\circ$ Let $S = \langle 5, 7, 11 \rangle = \{0, 5, 7, 10, 11, 12, 14, \rightarrow \}$ and $E = \{-4\} + S = \{-4, 1, 3, 6, 7, 8, 10, \rightarrow\}$. We have,

$$
E - S^* = \{z \in \mathbb{Z} ~ | ~ z + S^* \subseteq E\}
$$

The candidates are in the set $\{-9, -8, \ldots, 9\} \setminus E$, and checking the condition on each element, we get $E - S^* = \{5, 9\}$ and $t(E) = 2$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 10, 11, 15, 19 \rangle$ and $IS = \{20, 21, 25\} + S$, in GAP:

``` gap
gap> S := NumericalSemigroup(10, 11, 15, 19);
<Numerical semigroup with 4 generators>
gap> I := [20, 21, 25];
[ 20, 21, 25 ]
gap> IS := I + S;
<Ideal of numerical semigroup>
```

The function `Type` returns the type of a relative ideal of a numerical semigroup. This function also returns the type of a numerical semigroup.

``` gap
gap> Type(S);
4
gap> Type(IS);
2
```

If we want to know the elements of $(E - M) \setminus E$, we can apply the function `PseudoFrobenius`. This function also returns the set of pseudo-Frobenius numbers of a numerical semigroup.

``` gap
gap> PseudoFrobenius(IS);
[ 34, 48 ]
gap> PseudoFrobenius(S);
[ 23, 24, 27, 28 ]
```

## References
