---
title: "About Numerical Semigroups"
author: 
  - name: Ángel Álamo
engine: markdown
bibliography: Bibliography.bib
cls: apa
---

---
nocite: |
  @ns, @nsapp2, @JMDA
---

The first version of this wiki is the result of my internship in the Master's degree in Mathematics under the supervision of Pedro A. García-Sánchez.


The notion of numerical semigroup resides in the universe of natural numbers (taking into account the zero) with the usual addition operation. Formally, a numerical semigroup is a subset $S \subseteq \mathbb{N}$ such that fulfills the following conditions.

  - $(S, +)$ is closed under addition.
  
  - $0 \in S$.
  
  - $|\mathbb{N} \setminus S| < + \infty$.
  
Algebraically, a numerical semigroup is a submonoid $(S,+)$ of $(\mathbb{N}, +)$ adding the condition that $S$ has finite complement. In literature, this idea comes from trying to solve the following problem: given $n_1, \ldots, n_e, b$ positive integers, are there non-negative integers $\lambda_1, \ldots, \lambda_e \in \mathbb{N}$ such that

$$
\lambda_1 n_1 + \cdots + \lambda_e n_e = b?
$$
Moreover, there exists an integer $f$ such that $f$ cannot be expressed in terms of $n_1, \ldots, n_e$ but any number greater than $f$ can? The integer $f$ is known as the Frobenius number of $n_1, \ldots, n_e$.


If we consider $S = \langle n_1, \ldots, n_e \rangle$ the submonoid generated by $n_1, \ldots, n_e \rangle$ in $\mathbb{N}$, the problem is equivalent to determining when $b \in S$. The first main result of numerical semigroups is that for any numerical semigroup $S$, there exists a unique set of generators $P = \{n_1, \ldots, n_e\}$ such that $S = \langle n_1, \ldots, n_e \rangle$ and no proper subset of $P$ generates $S$. On the other hand, it can be proven that $\langle n_1, \ldots, n_e \rangle$ is a numerical semigroup if, and only if, $\gcd(n_1, \ldots, n_e) = 1$. Therefore, there exists the Frobenius number of $n_1, \ldots, n_e$ if, and only if, $\gcd(n_1, \ldots, n_e)$. Although the problem is easy to understand, its resolution is far from being simple. 


This wiki is intended to collect the definitions that has been arising in the study of numerical semigroups, ease the access to anyone interested in the topic, unify the notation used in different research papers and books, and ease to any researcher the search of a particular definition.


Having these objectives, everyone is welcome to collaborate in the wiki adding new definitions, fixing errors or suggesting new ideas forking the repository and requesting pull requests.

Each page has mainly one definition related to the concept of numerical semigroup, and it is structured as follows.

  - Definition: in this section are named the necessary definitions to introduce the concept and afterwards the concept is defined. Additionally, a proposition is added if it is necessary for its definition, or simple results to manage the concept or relate it with other definitions.
  
  - Examples: this sections is dedicated to develop one or more examples where the concept is used. This examples can be a particular case, an example to reaffirm or refute particular cases with the concept, or short proofs widely known in literature.
  
  - Examples with GAP: there is a package, NumericalSgps, which contains a large number of functions related to numerical semigroups. This section is dedicated to use the functions in package NumericalSgps related to the concept in particular cases.








