---
title: "Apéry set with respect to a set"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ns, @JMDA
---

<!-- Definición de Num. Sem. -->

## Definition

Let $C$ be a subset of $\mathbb{N}$ and $x \in \langle C \rangle \setminus \{0\}$. It is defined the Apéry set of $x$ in $C$, denoted by $Ap(C,x)$, as

$$
Ap(C,x) = \{s \in \langle C \rangle ~ | ~ s - x \not \in \langle C \rangle \}.
$$

This definition comes from the concept of [Apéry set of an element in a numerical semigroup](Apery-set.qmd).

## Examples

$\circ$ Let $C = \{5, 7, 13, 16 \}$, $C' := \langle C \rangle = \langle 5, 7, 13, 16 \rangle = \{0, 5, 7, 10, 12, \rightarrow \}$ and $x = 5$. If $s \ge 17$, it holds $s - x \in C'$, then $Ap(C, 5) \subseteq B$, where $B = \{0, 5, 7, 10, 12, 13, 14, 15, 16\}$. If we check the condition on each element of $B$, it is obtained that $Ap(C, 5) = \{0, 7, 13, 14, 16\}$. As $gcd(C) = 1$, $C'$ is a [numerical semigroup](Numerical-semigroup.qmd) and the definition of Apéry set of a set of integers and the Apéry set of a numerical semigroup are the same.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $C$ be a subset of $\mathbb{N}$ such that $gcd(C) = 1$ and $x \in \langle C \rangle \setminus \{0\}$, the function `NumericalSemigroup` generates the numerical semigroup generated by $C$. On the other hand, the function`AperyList` returns the Apéry set of $x$ in $C$.

``` gap
gap> C := NumericalSemigroup(9, 24, 31, 35);
<Numerical semigroup with 4 generators>
gap> AperyList(C, 9);
[ 0, 55, 83, 48, 31, 59, 24, 70, 35 ]
```

## References

::: {#refs}

:::