---
title: "Arf system of generators"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ANS, @JMDA
---

<!--  Arf_NS -->

## Definition

Let $S$ be an [Arf](../Families-NS/Arf-semigroup.qmd) [numerical semigroup](Numerical-semigroup.qmd) and $M = \{m_1, \ldots, m_k\}$ a set of positive integers with $\gcd(M) = 1$ and $m_1 < \ldots < m_k$. It is said that $M$ is an Arf system of generators of $S$ if the [Arf closure](Arf-closure.qmd) of $M$ is $S$. If no proper subset of $M$ has Arf closure $S$, then it is said that $M$ is minimal. This definition is a particular case of [V-monoids generated by a subset](../Varieties-NS/V-monoid-generated.qmd).


It can be proven that for any Arf numerical semigroup $S$, there exists a finite and unique minimal Arf system of generators $M$ such that the Arf closure of $M$ is $S$. Moreover, $M$ is a subset of the [minimal set of generators](Minimal-set-of-generators.qmd) of $S$.


## Examples

$\circ$ Let us consider the Arf semigroup $S = \langle 4, 6, 7, 9 \rangle = \{0, 3, 6, \rightarrow\}$. From the condition $gcd(M) = 1$, the candidates are

$$
M_1 = \{4, 7\}, ~~ M_2 = \{4, 9\}, ~~ M_3 = \{6, 7\}, ~~ M_4 = \{7,9\},
$$

$$
M_5 = \{4, 6, 7\}, ~~ M_6 = \{4, 6, 9\}, ~~ M_7 = \{6, 7, 9\}, ~~ M_8 = \{4, 6, 7, 9\}.
$$ 

Computing the Arf closure of each $M_j$ for $j \in \{1, \dots, 8\}$, it is obtained that $M_5 = \{4, 6, 7\}$ is the Arf system of generators of $S$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 8, 10, 12, 14, 19, 21, 23, 25 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(8, 10, 12, 14, 19, 21, 23, 25);
<Numerical semigroup with 8 generators>
```

Given a numerical semigroup $S$, the function `IsArf` returns true if $S$ is an Arf numerical semigroup and false otherwise.

``` gap
gap> IsArf(S);
true
```

Given a numerical semigroup $S$, the functions `ArfCharactersOfArfNumericalSemigroup` and `MinimalArfGeneratingSystemOfArfNumericalSemigroup` return the Arf system of generators of $S$.

``` gap
gap> ArfCharactersOfArfNumericalSemigroup(S);
[ 8, 10, 19 ]
gap> MinimalArfGeneratingSystemOfArfNumericalSemigroup(S);
[ 8, 10, 19 ]
```

## References

::: {#refs}

:::
