---
title: "Arf closure"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

<!-- Appl -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) and let $\mathcal{O}(S)$ be the set of [oversemigroups](Oversemigroup.qmd) of $S$. It is defined the Arf closure of $S$ as the smallest [Arf numerical semigroup](../Families-NS/Arf-semigroup.qmd) containing $S$, and it is denoted by $Arf(S)$.

It can be proven that the intersection of Arf semigroups is also an Arf semigroup, from which it follows that the Arf closure is the intersection of all Arf numerical semigroups containing it. Since $\mathcal{O}(S)$ is finite, the intersection is also finite.

## Examples

$\circ$ If $S$ is an Arf semigroup, then $Arf(S) = S$.

$\circ$ Let $S = \langle 4, 6, 9 \rangle = \{0, 4, 6, 8, 9, 10, 12, \rightarrow \}$. The set of oversemigroups is

$$
\mathcal{O}(S) = \{\mathbb{N}, \{0, 2, \rightarrow \}, \{0, 2, 4, \rightarrow \}, \{0, 2, 4, 6, \rightarrow\}, \{0, 2, 4, 6, 8, \rightarrow \}, \{0, 3, \rightarrow \},
$$

$$
\{0, 3, 4, 6, \rightarrow \}, \{0, 4, \rightarrow \}, \{0, 4, 5, 6, 8, \rightarrow \}, \{0, 4, 6, \rightarrow \}, \{0, 4, 6, 8, \rightarrow \}, S \}.
$$

Moreover, the Arf semigroups are

$$
T_0 = \mathbb{N}, T_1 = \{0, 2, \rightarrow \}, T_2 = \{0, 2, 4, \rightarrow \}, T_3 = \{0, 2, 4, 6, \rightarrow \}, T_4 = \{0, 2, 4, 6, 8, \rightarrow \}, 
$$

$$
T_5 = \{0, 3, \rightarrow \}, T_6 = \{0, 4, \rightarrow \}, T_7 = \{0, 4, 6, \rightarrow \}, T_8 = \{0, 4, 6, 8, \rightarrow \}.
$$

Therefore, the Arf closure of $S$ is $A = \bigcap_{i = 0}^8 T_i = \{0, 4, 6, 8, \rightarrow \} = S \cup \{11\}$. In this case, the Arf closure of $S$ is the numerical semigroup $S$ to which its [Frobenius number](Frobenius-number.qmd) has been added.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 15, 32, 49 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(15, 32, 49);
<Numerical semigroup with 3 generators>
```

The functions `ArfClosure` and `ArfNumericalSemigroupClosure` compute the Arf closure of a numerical semigroup.

``` gap
gap> A := ArfClosure(S);
<Numerical semigroup>
gap> SmallElements(A);
[ 0, 15, 30, 32, 34, 36, 38, 40, 42, 44 ]
gap> ArfClosure(S) = ArfNumericalSemigroupClosure(S);
true
```

The function `SmallElements` returns a list with the [left elements](Left-elements.qmd) and the [conductor](Conductor.qmd) of the numerical semigroup. Then, the Arf closure of $S$ is $A = \{0,15, 30, 32, 34, 36, 38, 40, 42, 44, \rightarrow \}$.

$\diamond$ Let $S = \langle 4, 14, 19, 21 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4, 14, 19, 21);
<Numerical semigroup with 4 generators>
```

Given an Arf numerical semigroup $S$, the function `ArfOverSemigroups` returns a list of Arf oversemigroups of $S$.

``` gap
gap> A := ArfOverSemigroups(S);
[ <The numerical semigroup N>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators> ]
gap> List(A, l -> MinimalGenerators(l));
[ [ 1 ], [ 2, 3 ], [ 2, 5 ], [ 2, 7 ], [ 2, 9 ], [ 2, 11 ],
  [ 2, 13 ], [ 2, 15 ], [ 2, 17 ], [ 2, 19 ], [ 3 .. 5 ],
  [ 4 .. 7 ], [ 4, 6, 7, 9 ], [ 4, 6, 9, 11 ],
  [ 4, 6, 11, 13 ], [ 4, 6, 13, 15 ], [ 4, 6, 15, 17 ],
  [ 4, 6, 17, 19 ], [ 4, 6, 19, 21 ], [ 4, 7, 9, 10 ],
  [ 4, 9, 10, 11 ], [ 4, 10, 11, 13 ], [ 4, 10, 13, 15 ],
  [ 4, 10, 15, 17 ], [ 4, 10, 17, 19 ], [ 4, 10, 19, 21 ],
  [ 4, 11, 13, 14 ], [ 4, 13, 14, 15 ], [ 4, 14, 15, 17 ],
  [ 4, 14, 17, 19 ], [ 4, 14, 19, 21 ] ]
```

## References

::: {#refs}

:::