---
title: "Cocycle"
format: html
engine: markdown
---

<!-- Parametrizing_Arf_NS -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $n \in S \setminus \{0\}$. If $w(i)$ denotes the smallest element in $S$ such that $w(i) \equiv i ~~ (mod ~ n)$ for all $i \in \{0, \ldots, n-1\}$ and $\overline{m} = m ~ (mod ~ n)$ for all $m \in \mathbb{N}$, it is defined the cocycle of $S$ with respect to $n$, denoted by $H(S,n)$, as the matrix $H(S,n) = (h_{i,j})_{i, j = 0}^{n-1}$, where $h_{i,j}$ is defined as

$$
h_{i,j} = \frac{w(i) + w(j) - w\left(\overline{i+j}\right)}{n}.
$$

It can be proven that $h_{i,j} \in \mathbb{N}$ for all $i,j \in \{0, \ldots, n-1\}$.

## Examples

$\circ$ Let $S = \langle 5, 9, 11, 12 \rangle = \{0, 5, 9, 10, 11, 12, 14, \rightarrow\}$ and $n = 5$. It is well known that $Ap(S,n) = \{w(0) = 0, w(1), \ldots, w(n-1)\}$, where $Ap(S,n)$ denotes the [Apéry list](Apery-set.qmd) of $S$ with respect to $n$. Since $Ap(S,5) = \{0, 9, 11, 12, 18\}$, it is deduced that

$$
w(0) = 0, ~ w(1) = 11, ~ w(2) = 12, ~w(3) = 18, ~w(4) = 9,
$$

and the cocycle of $S$ with respect to $n = 5$ is

$$
H(S,5) = \begin{pmatrix}
  0 & 0 & 0 & 0 & 0 \\
  0 & 2 & 1 & 4 & 4 \\
  0 & 1 & 3 & 6 & 2 \\
  0 & 4 & 6 & 5 & 3 \\
  0 & 4 & 2 & 3 & 0 \\
\end{pmatrix}.
$$

The symmetry of the cocycle comes from the definition.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 6, 15, 17, 22 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(6, 15, 17, 22);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$ and an element $n \in S \setminus \{0\}$, the function `CocycleOfNumericalSemigroupWRTElement` returns the cocycle of $S$ with respect to $n$.

``` gap
gap> CocycleOfNumericalSemigroupWRTElement(S, 6);
[ [ 0, 0, 0, 0, 0, 0 ], [ 0, 7, 9, 5, 7, 9 ],
  [ 0, 9, 7, 5, 9, 2 ], [ 0, 5, 5, 5, 0, 0 ],
  [ 0, 7, 9, 0, 2, 4 ], [ 0, 9, 2, 0, 4, 2 ] ]
```

Therefore, the cocycle of $S$ with respect to $n = 6$ is

$$
H(S, 6) = \begin{pmatrix}
  0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 7 & 9 & 5 & 7 & 9 \\
  0 & 9 & 7 & 5 & 9 & 2 \\
  0 & 5 & 5 & 5 & 0 & 0 \\
  0 & 7 & 9 & 0 & 2 & 4 \\
  0 & 9 & 2 & 0 & 4 & 2 \\
\end{pmatrix}.
$$

## References
