---
title: "Conductor"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd). It is said that $s \in S$ is the conductor of $S$ if is the least integer which satisfies that for any $n \in \mathbb{N}$, it holds $s + n \in S$, and it is denoted by $C(S)$ or $\chi(S)$. Equivalently, $s \in S$ is the conductor of $S$ if $s-1 \not \in S$ and for all $n \in \mathbb{N}$ such that $n \ge s$, it holds $n \in S$.

There is a obvious relation between the conductor and the [Frobenius number](Frobenius-number.qmd), that is, $F(S) + 1 = C(S)$. The conductor does not determine in general the numerical semigroup, that means, it may exist more than one numerical semigroup with the same conductor.

## Examples

$\circ$ Let us consider a non-zero $m \in \mathbb{N}$ arbitrary but fixed and $S = \{0, m, \rightarrow\}$. Obviously, $C(S) = m$ and in this case every element of $S \setminus \{0\}$ is greater or equal than the conductor. This kind of numerical semigroups are the only ones that satisfy this property. This example shows that for any $n \in \mathbb{N}$ with $n \ne 1$, there exists a numerical semigroup $S$ such that $C(S) = n$.

$\circ$ Let $S_1 = \langle 5, 7, 9 \rangle$ and $S_2 = \langle 2, 15 \rangle$. With simple calculations we obtain that $S_1 = \{0, 5, 7, 9, 10, 12, 14, \rightarrow \}$ and $S_2 = \{0, 2,4,6,8,10,12,14, \rightarrow\}$, therefore $C(S_1) = 14 = C(S_2)$ and $S_1 \ne S_2$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 3, 7, 9, 11 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(3, 7, 9, 11);
<Numerical semigroup with 4 generators>
```

Using the `Conductor` function, we can obtain the conductor of $S$.

``` gap
gap> Conductor(S);
9
```

Taking into account the equality $F(S) + 1 = C(S)$, we can compute the conductor from the Frobenius number. The function `FrobeniusNumber` compute the Frobenius number of $S$.

``` gap
gap> FrobeniusNumber(S) + 1;
9
```

$\diamond$ Let $S = \langle 4, 20, 21, 22 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4, 20, 21, 22);
<Numerical semigroup with 4 generators>
```

The function `SmallElements` returns a list with the [left elements](Left-elements.qmd) and the conductor of $S$.

``` gap
gap> SmallElements(S);
[ 0, 4, 8, 12, 16, 20, 21, 22, 24, 25, 26, 28, 29, 30, 32, 33, 34, 36, 37, 38, 40 ]
```

We obtain $C(S) = 40$, we can check it with the function `Conductor`.

``` gap
gap> Conductor(S);
40
```

## References

::: {#refs}

:::
