---
title: "Degrees of a primitive element"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @CPMNS, @JMDA
---


<!--  -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) [minimally generated](Minimal-set-of-generators.qmd) by $P(S) = \{n_1, \ldots, n_e\}$. Let us define $M \subseteq \mathbb{N}^{2e}$ as the set of all solutions of the equation

$$
P \cdot x - P \cdot y = 0 \Longleftrightarrow (n_1, \ldots, n_e) \cdot x - (n_1, \ldots, n_e) \cdot y = 0,
$$

where $x,y \in \mathbb{N}^e$ and the dot denotes the usual dot product. From the definition, if $(x,y) \in M$, then $x,y \in \mathbf{Z}(s)$ for a certain $s \in S$, where $\mathbf{Z}(s)$ denotes the set of [factorizations](../Presentations-NS/Set-of-factorizations.qmd) of $s$ in $S$.

It can be proven that $M$ is a monoid, and then there exists a unique minimal system of generators $P_M$. It is defined the primitive elements of $S$ as the elements of $P_M$, and the degree of a primitive element as the elements $s \in S$ such that $(x,y) \in \mathbf{Z}(s)$ for some $(x,y) \in P_M$. If $(x,y) \in P_M$ is such that $|x| \le |y|$, where $|x|, |y|$ denotes the [lengths](../Fact-and-div/Length-factorization.qmd) of $x$ and $y$ respectively, it is said that $s$ is a monotone degree of a primitive element.

It can be proven that [Betti elements](../Presentations-NS/Betti-element.qmd) are primitive.

## Examples

$\circ$ Let $S$ be a numerical semigroup minimally generated by $P = \{n_1, \ldots, n_e\}$ and $M$ the set of solutions of the equation $p \cdot x - P \cdot y = 0$, minimally generated by $P_M$. If $e_i \in \mathbb{N}^e$ is such that the unique coordinate nonzero is $i-$th coordinate with value one, then $(e_i, e_i)$ is a primitive element. Indeed, the pair $(e_i, e_i)$ is a solution, since

$$
P \cdot e_i - P \cdot e_i = n_i - n_i = 0,
$$

and is minimal for the fact that if $(e_i,e_i) = (x,y) + (x,t)$ for some $(x,y), (z,t) \in M$, then $(x,y) = (0,0)$ or $(z,t) = (0,0)$. This example shows that there are primitive elements that are not [minimal relations](../Presentations-NS/Presentation-NS.qmd) of $S$.

$\circ$ Let $S = \langle 4, 6, 11 \rangle$. The primitive elements of $S$ are the minimal solutions of the equation

$$
4(x_1 - y_1) + 6(x_2 - y_2) + 11(x_3 - y_3) = 0.
$$

Applying elimination theorem and extension theorem from ring theory in several indeterminate, it is obtained that

$$
M = \langle (1,0,0,1,0,0), (0,1,0,0,1,0), (0, 0, 2, 1, 3, 0), (0, 0, 2, 4, 1, 0),
  (0, 0, 4, 11, 0, 0), (0, 0, 6, 0, 11, 0), \\
$$

$$ 
(0, 1, 2, 7, 0, 0), (0, 2, 0, 3, 0, 0), (0, 5, 0, 2, 0, 2), (0, 8, 0, 1, 0, 4), (0,0,1,0,0,1) \rangle,
$$

and the degree of primitive elements of $S$ is $\{4, 6, 11, 12, 22, 28, 30, 44, 48, 66\}$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 5, 9, 13, 16 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(5, 9, 13, 16);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$, the function `DegreesOfPrimitiveElementsOfNumericalSemigroup` returns the set of degrees of primitive elements of $S$.

``` gap
gap> DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 5, 9, 13, 16, 18, 25, 26, 29, 31, 32, 35, 36, 39, 40, 41, 42, 45, 48, 52, 53, 55, 57, 58,
  63, 64, 65, 68, 78, 80, 81, 85, 90, 91, 96, 104, 112, 117, 130, 144, 169, 208 ]
```

$\diamond$ Let $S = \langle 3, 8, 10 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(3, 8, 10);
<Numerical semigroup with 3 generators>
```

Given a numerical semigroup $S$ minimally generated by $P$, the function `DegreesOfEqualPrimitiveElementsOfNumericalSemigroup` returns the set of degrees of primitive elements $s$ in $S$ so that there exists $(x,y) \in P_M \cap \mathbf{Z}(s)$ with $|x| = |y|$. Furthermore, the function `DegreesOfMonotonePrimitiveElementsOfNumericalSemigroup` computes the monotone degrees of primitive elements.

``` gap
gap> DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 16, 18, 20, 24, 30, 40 ]
gap> DegreesOfEqualPrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 56 ]
gap> DegreesOfMonotonePrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 16, 18, 20, 24, 30, 40, 56 ]
```

$\diamond$ Given $M$ and $m$ integers, the function `NumericalSemigroupsWithMaxPrimitiveAndMultiplicity` returns a list of numerical semigroups with maximum $M$ primitive elements and [multiplicity](Multiplicity.qmd) $m$.

``` gap
gap> N := NumericalSemigroupsWithMaxPrimitiveAndMultiplicity (20, 7);;
gap> Length(N);
96
gap> S := N[96];
<Numerical semigroup with 3 generators>
gap> D := DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 7, 19, 20, 40, 76, 77, 95, 98, 114, 119, 133, 140, 247, 380 ]
gap> Length(D);
14
gap> Multiplicity(S);
7
```

Moreover, given an integer $M$, the function `NumericalSemigroupsWithMaxPrimitive` returns a list with of numerical semigroups with maximum primitive $M$.

``` gap
gap> T := NumericalSemigroupsWithMaxPrimitive(10);
[ <Numerical semigroup with 2 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 5 generators>, <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 2 generators> ]
gap> Length(T);
17
```

## References

::: {#refs}

:::
