---
title: "Degrees of primitive elements"
format: html
engine: markdown
---

<!--  -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) [minimally generated](Minimal-set-of-generators.qmd) by $P(S) = \{n_1, \ldots, n_e\}$. it is said that $s \in S$ is a degree of primitive elements in $S$ if there exists a minimal solution to

$$
P \cdot x - P \cdot y = 0 \Longleftrightarrow (n_1, \ldots, n_e) \cdot x - (n_1, \ldots, n_e) \cdot y = 0,
$$

where $x,y$ are [factorizations](../Presentations-NS/Set-of-factorizations.qmd) of $s$ in $S$ and the dot product is the usual vector scalar product.

It can be proven that [Betti elements](../Presentations-NS/Betti-element.qmd) are primitive, and as a consequence every numerical semigroup has a primitive element.

## Examples

$\circ$ Let $S = \langle \rangle$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 5, 9, 13, 16 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(5, 9, 13, 16);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$, the function `DegreesOfPrimitiveElementsOfNumericalSemigroup` returns the degrees of primitive elements of $S$.

``` gap
gap> DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 5, 9, 13, 16, 18, 25, 26, 29, 31, 32, 35, 36, 39, 40, 41, 42, 45, 48, 52, 53, 55, 57, 58,
  63, 64, 65, 68, 78, 80, 81, 85, 90, 91, 96, 104, 112, 117, 130, 144, 169, 208 ]
```

$\diamond$ Let $S = \langle 3, 8, 10 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(3, 8, 10);
<Numerical semigroup with 3 generators>
```

Given a numerical semigroup $S$ minimally generated by $P$, the function `DegreesOfEqualPrimitiveElementsOfNumericalSemigroup` returns the set of elements $s$ in $S$ such that there exist a minimal solution of $P \cdot x - P \cdot y = 0$ with $x,y$ factorizations of $s$ and of the same [length](../Fact-and-div/Length-factorization.qmd). Furthermore, the function `DegreesOfMonotonePrimitiveElementsOfNumericalSemigroup` computes the elements $s$ in $S$ such that there exist a minimal solution of $P \cdot x - P \cdot y = 0$ with $x,y$ factorizations of $s$ with lengths $|x| \le |y|$.

``` gap
gap> DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 16, 18, 20, 24, 30, 40 ]
gap> DegreesOfEqualPrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 56 ]
gap> DegreesOfMonotonePrimitiveElementsOfNumericalSemigroup(S);
[ 3, 8, 10, 16, 18, 20, 24, 30, 40, 56 ]
```

$\diamond$ Given $M$ and $m$ integers, the function `NumericalSemigroupsWithMaxPrimitiveAndMultiplicity` returns a list of numerical semigroups with maximum $M$ primitive elements and [multiplicity](Multiplicity.qmd) $m$.

``` gap
gap> N := NumericalSemigroupsWithMaxPrimitiveAndMultiplicity (20, 7);;
gap> Length(N);
96
gap> S := N[96];
<Numerical semigroup with 3 generators>
gap> D := DegreesOfPrimitiveElementsOfNumericalSemigroup(S);
[ 7, 19, 20, 40, 76, 77, 95, 98, 114, 119, 133, 140, 247, 380 ]
gap> Length(D);
14
gap> Multiplicity(S);
7
```

Moreover, given an integer $M$, the function `NumericalSemigroupsWithMaxPrimitive` returns a list with of numerical semigroups with maximum primitive $M$.

``` gap
gap> T := NumericalSemigroupsWithMaxPrimitive(10);
[ <Numerical semigroup with 2 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 4 generators>,
  <Numerical semigroup with 5 generators>, <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 3 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 4 generators>, <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 2 generators> ]
gap> Length(T);
17
```

## References
