---
title: "Dominant"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) with positive [conductor](Conductor.qmd) $C(S)$. It is defined the dominant of $S$, denoted by $d(S)$, as $d(S) = \max \{s \in S ~ | ~ s < C(S)\}$.

## Examples

$\circ$ Let $S = \langle 3, 7, 11 \rangle$. We have that $9, 10, 11 \in S$ and $8 \not \in S$, therefore the conductor is $C(S) = 9$, and the dominant is $d(S) = 7$. This numerical semigroup is also [acute](../Families-NS/NS-Acute.qmd), since $C(S) - d(S) = 2$.

## Examples with GAP

Nowadays, there are no functions in package NumericalSgps related to dominant of a numerical semigroup. However, the following function in GAP returns the dominant of a given numerical semigroup.

``` gap
gap> DominantOfNumericalSemigroup := function(S)
>       if IsNumericalSemigroup(S) = false then
>               return "The input must be a Numerical Semigroup";
>       elif Conductor(S) < 0 then
>               return "The conductor must be a positive integer";
>       else
>               n := Length(SmallElements(S));
>               return SmallElements(S)[n-1];
>       fi;
> end;
function( S ) ... end
```

First, we check if the input is a numerical semigroup with the function `IsNumericalSemigroup`. Afterwards, we check if $S$ is a numerical semigroup with positive conductor. Finally, since the function `SmallElements` returns an ordered list formed by the [left elements](Left-elements.qmd) and the conductor of the given numerical semigroup, the penultimate element of the list is the dominant.

$\diamond$ Let $S = \langle 7, 22, 47, 52 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(7, 22, 47, 52);
<Numerical semigroup with 4 generators>
```

If we compute the small elements of $S$,

``` gap
gap> SmallElements(S);
[ 0, 7, 14, 21, 22, 28, 29, 35, 36, 42, 43, 44, 47, 49, 50, 51,
  52, 54, 56, 57, 58, 59, 61, 63, 64, 65, 66, 68 ]
```

Then, the dominant of $S$ is $d(S) = 66$. With the function defined above,

``` gap
gap> DominantOfNumericalSemigroup(S);
66
```

The only numerical semigroup with no positive conductor is $S = \mathbb{N}$, in this case,

``` gap
gap> T := NumericalSemigroup(1);
<The numerical semigroup N>
gap> DominantOfNumericalSemigroup(T);
"None"
```

If $S$ is not a numerical semigroup,

``` gap
gap> DominantOfNumericalSemigroup(3);
"The input must be a Numerical Semigroup"
```

## References

<!-- https://docs.gap-system.org/doc/tut/chap4_mj.html#X801EE07E839B31B2 -->
