---
title: "Embedding dimension"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd). It is well known that every numerical semigroup admits a unique finite [minimal system of generators](Minimal-set-of-generators.qmd) $P(S) = \{n_1, n_2, \ldots, n_e\}$ for some $e \in \mathbb{N} \setminus \{0\}$. The embedding dimension is defined as the cardinal of the minimal system of generators, and it is denoted by $e(S), |P(S)|$ or $d(S)$.

It can be proven that $e(S) \le m(S)$, where $m(S)$ denotes the [multiplicity](Multiplicity.qmd) of $S$. If $e(S) = m(S)$, it is said that $S$ is a numerical semigroup with [maximal embedding dimension](../Families-NS/NS-maximal-embedding-dimension.qmd).

## Examples

$\circ$ Let $S = \{0, 3, 6, 7, 9, 10, 12, \rightarrow\}$. First, we will compute the minimal system of generators of $S$. The multiplicity of $S$ is $m(S) = 3$ and is always a minimal generator. On the other hand, the number $7$ cannot be generated by $3$, then $7$ is another minimal generator. Considering the generators system $B = \{3, 7\}$, we obtain $S$. Therefore, $e(S) = |B| = 2$.

$\circ$ Let us consider $m \in \mathbb{N} \setminus \{0\}$ arbitrary but fixed and $S = \langle m, m+1, m+2, \ldots, 2m - 1 \rangle$. It is easy to see that $B = \{m, m+1, m+2, \ldots, 2m - 1\}$ is a minimal system of generators of $S$. Therefore $e(S) = m = m(S)$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 5, 12, 15, 17, 18, 19, 29, 35, 50 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(5, 12, 15, 17, 18, 19, 29, 35, 50);
<Numerical semigroup with 9 generators>
```

The functions `EmbeddingDimension` and `EmbeddingDimensionOfNumericalSemigroup` compute the embedding dimension of $S$.

``` gap
gap> EmbeddingDimension(S);
4
gap> EmbeddingDimensionOfNumericalSemigroup(S);
4
```

Using the `MinimalGenerators` function, we can also obtain the minimal system of generators of $S$.

``` gap
gap> MinimalGenerators(S);
[ 5, 12, 18, 19 ]
```

## References
