---
title: "Frobenius number"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd). It is defined the Frobenius number of $S$, denoted by $F(S)$ or $g(S)$, as the maximum of the set $\mathbb{N} \setminus S$. Equivalently, the Frobenius number is the largest number that does not belong to $S$ or the unique element in $\mathbb{N} \setminus S$ so that for any $n \in \mathbb{N} \setminus \{0\}$, we have that $F(S) + n \in S$.

There is a obvious relation between the [conductor](Conductor.qmd) and the Frobenius number, that is, $F(S) + 1 = C(S)$. The Frobenius number does not determine in general the numerical semigroup, that means, it may exist more than one numerical semigroup with the same Frobenius number.

## Examples

$\circ$ Let us consider a non-zero $m \in \mathbb{N}$ arbitrary but fixed and $S = \{0, m, \rightarrow\}$. Obviously, $F(S) = m-1$ and in this case every element of $S \setminus \{0\}$ is greater than the Frobenius number. This kind of numerical semigroups are the only ones that satisfy this property. This example shows that for any $n \in \mathbb{N} \setminus \{0\}$, there exists a numerical semigroup $S$ so that $F(S) = n$.

$\circ$ Let $S_1 = \langle 5, 7, 9 \rangle$ and $S_2 = \langle 2, 15 \rangle$. With simple calculations we obtain that $S_1 = \{0, 5, 7, 9, 10, 12, 14, \rightarrow \}$ and $S_2 = \{0, 2,4,6,8,10,12,14, \rightarrow\}$, therefore $F(S_1) = 13 = F(S_2)$ and $S_1 \ne S_2$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 3, 10, 16, 19 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(3, 10, 16, 19);
<Numerical semigroup with 4 generators>
```

The functions `FrobeniusNumber` and `FrobeniusNumberOfNumericalSemigroup` compute the Frobenius number of $S$.

``` gap
gap> FrobeniusNumber(S);
17
```

Taking into account the equality $F(S) + 1 = C(S)$, we can compute the Frobenius number from the conductor. The function `Conductor` computes the conductor of $S$.

``` gap
gap> Conductor(S) - 1;
17
```

$\diamond$ Let $S = \langle 4, 20, 21, 22 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4, 20, 21, 22);
```

Using the function `SmallElements` we can obtain the [left elements](Left-elements.qmd) and the conductor of $S$.

``` gap
gap> SmallElements(S);
[ 0, 4, 8, 12, 16, 20, 21, 22, 24, 25, 26, 28, 29, 30, 32, 33, 34, 36, 37, 38, 40 ]
```

We obtain $F(S) = C(S) - 1 = 40 - 1 = 39$.

``` gap
gap> FrobeniusNumber(S);
39
```

If we want to know how many numerical semigroups have Frobenius number $f \in \mathbb{N}$, we have the function `NumericalSemigroupsWithFrobeniusNumberFG` that returns the set of these numerical semigroups. For $f = 15$,

``` gap
gap> Length(NumericalSemigroupsWithFrobeniusNumberFG(15));
200
```

## References
