---
title: "Fundamental gap"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) and let $G(S)$ be the set of [gaps](Gap.qmd) of $S$. A gap $g \in G(S)$ is a fundamental gap of $S$ if $\{2g, 3g\} \subseteq S$, or equivalently, for every $n \in \mathbb{N} \setminus \{0,1\}$, it holds that $ng \in S$. It is denoted by $FG(S)$ the set of fundamental gaps of $S$ and is always non-empty, due to $F(S) \in FG(S)$, where $F(S)$ is the [Frobenius number](Frobenius-number.qmd) of $S$.

It can be proven that $FG(S)$ determines the numerical semigroup $S$.

## Examples

$\circ$ Let $S = \langle 4, 9, 10 \rangle = \{0, 4, 8, 9, 10, 12, 13, 14, 16, \rightarrow \}$. We have that $G(S) = \{1, 2, 3, 5, 6, 7, 11, 15\}$ and checking the condition for each gap of $S$, it is concluded that $FG(S) = \{6, 7, 11, 15\}$.

$\circ$ Let us consider $b \in \mathbb{N}$ an odd element arbitrary but fixed. The set $S = \langle 2, b \rangle$ is a numerical semigroup (note that if $n \ge b$, then $n \in S$) and the gaps of $S$ are $G(S) = \{1, 3, 5, 7, \ldots, b - 2\}$, in other words, all the odd naturals smaller than $b$. Now, a gap $x \in G(S)$ is fundamental if $\{2x,3x\} \subseteq S$, in this case, as $2 \in S$, then $2x \in S$ for all $x \in G(S)$. On the other hand, $3x \in S$ if, and only if, $x \ge \lceil \frac{b}{3} \rceil$, therefore, $FG(S)$ consist in all the odd integers greater or equal to $\lceil \frac{b}{3} \rceil$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 8, 12, 14, 15, 25 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(8, 12, 14, 15, 25);
<Numerical semigroup with 5 generators>
```

The functions `FundamentalGaps` and `FundamentalGapsOfNumericalSemigroup` return the set of fundamental gaps of $S$.

``` gap
gap> FundamentalGaps(S);
[ 4, 10, 11, 13, 17, 18, 19, 21 ]
gap> FundamentalGaps(S) = FundamentalGapsOfNumericalSemigroup(S);
true
```

If we want to know all the gaps of $S$, then we have the function `Gaps`.

``` gap
gap> Gaps(S);
[ 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 17, 18, 19, 21 ]
```

$\diamond$ Given a list of positive integers, the function `NumericalSemigroupByFundamentalGaps` returns the numerical semigroup determined by the list if it is possible, which is considered as the list of fundamental gaps.

``` gap
gap> l := [6,8,13,15,17,20,22,29];
[ 6, 8, 13, 15, 17, 20, 22, 29 ]
gap> S := NumericalSemigroupByFundamentalGaps(l);
<Numerical semigroup>
gap> MinimalGenerators(S);
[ 7, 9, 12 ]
```

The function `MinimalGenerators` returns a list with the [minimal generators](Minimal-set-of-generators.qmd) of the numerical semigroup. Then, $S = \langle 7, 9, 12 \rangle$ and $FG(S) = \{6, 8, 13, 15, 17, 20, 22, 29\}$.

## References

<!-- Num. Sem -->
