---
title: "Kunz polytope"
format: html
engine: markdown
---

<!-- referencia CAGB02 en NumGAP, 3.1-20 // NS-and-Kunz-polytope -->

## Definition

Let $m$ and $g$ be positive integers. It is defined the Kunz polytope, denoted by $K(m,g)$, as the system of equations

$$
\begin{cases}
  x_i \ge 1 & \text{for all } ~ i = 1, 2, \ldots, m-1, \\
  x_i + x_j - x_{i+j} \ge 0 & \text{for all } ~ 1 \le i \le j \le m-1 ~ \text{and} ~ i + j \le m-1, \\
  x_i + x_j - x_{i+j-m} \ge -1 & \text{for all } ~ 1 \le i \le j \le m-1 ~ \text{and} ~ i + j \ge m+1, \\
  x_1 + x_2 + \cdots + x_{m-1} = g.
\end{cases}
$$

It can be proven that there is one-to-one correspondence between the number of [numerical semigroups](Numerical-semigroup.qmd) with [multiplicity](Multiplicity.qmd) $m$ and [genus](Genus.qmd) $g$ and the set of positive integers $(x_1, \ldots, x_{m-1})$ that are solutions of the Kunz polytope.

## Examples

$\circ$ Let us consider the numerical semigroup $S = \langle 3, 7, 11 \rangle$, which has multiplicity $m(S) = 3$ and genus $g(S) = 5$. Let us see that the [Kunz coordinates](Kunz-coordinates.qmd) of $S$ is a solution of the Kunz polytope $K(3,5)$. The [Apéry set](Apery-set.qmd) of $S$ with respect to $m$ is $Ap(S,3) = \{0, 7, 11\}$ and $7 = 2 \cdot 3 + 1, 11 = 3 \cdot 3 + 2$. Then, the Kunz coordinates of $S$ is $(x_1, x_2) = (2,3)$. On the other hand, the Kunz polytope $K(3, 5)$ is the following system of equations.

$$
\begin{cases}
  x_1 \ge 1, \\
  x_2 \ge 1, \\
  2x_1 - x_2 \ge 0, \\
  -x_1 + 2x_2 \ge -1, \\
  x_1 + x_2 = 5.
\end{cases}
$$

We have that $2 \ge 1, ~ 3 \ge 1, ~ 2 \cdot 2 - 3 = 1 \ge 0, ~-2 + 2 \cdot 3 = 4 \ge -1$ and $2 + 3 = 5$, concluding that $(2,3)$ is an integer solution of $K(3,5)$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Given a positive integer $m$, the function `KunzPolytope` returns the matrix $(A | -b)$ such that $Ax \ge b$ is the Kunz polytope removing the condition $x_1 + \cdots + x_{m-1} = g$.

``` gap
gap> L := KunzPolytope(5);
[ [ 1, 0, 0, 0, -1 ], [ 0, 1, 0, 0, -1 ], [ 0, 0, 1, 0, -1 ], [ 0, 0, 0, 1, -1 ],
  [ 2, -1, 0, 0, 0 ], [ 1, 1, -1, 0, 0 ], [ 1, 0, 1, -1, 0 ], [ 0, 2, 0, -1, 0 ],
  [ -1, 1, 0, 1, 1 ], [ -1, 0, 2, 0, 1 ], [ 0, -1, 1, 1, 1 ], [ 0, 0, -1, 2, 1 ] ]
```

Therefore, the Kunz polytope $K(m,g)$ would be

$$
\begin{pmatrix}
  1 & 0 & 0 & 0 & -1 \\
  0 & 1 & 0 & 0 & -1 \\
  0 & 0 & 1 & 0 & -1 \\
  0 & 0 & 0 & 1 & -1 \\
  2 & -1 & 0 & 0 & 0 \\
  1 & 1 & -1 & 0 & 0 \\
  1 & 0 & 1 & -1 & 0 \\
  0 & 2 & 0 & -1 & 0 \\
  -1 & 1 & 0 & 1 & 1 \\
  -1 & 0 & 2 & 0 & 1 \\
  0 & -1 & 1 & 1 & 1 \\
  0 & 0 & -1 & 2 & 1 \\
  1 & 1 & 1 & 1 & -g \\
\end{pmatrix}
\begin{pmatrix}
  x_1 \\
  x_2 \\
  x_3 \\
  x_4 \\
  1 \\
\end{pmatrix}
\ge 
\begin{pmatrix}
  0 \\
  0 \\
  0 \\
  0 \\
  0 \\
  0 \\
\end{pmatrix}.
$$

## References
