---
title: "L-shape of Apéry set"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @JMDA, @AGUILOGOST20152168
---

<!-- vertices_L_shape  -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) [minimally generated](Minimal-set-of-generators.qmd) by $P(S) = \{n_1, \ldots, n_e\}$ and $m \in S \setminus \{0\}$. It is said that $L \subseteq \mathbb{N}^e$ is an $L-$shape associated to $Ap(S,m)$ if the following two properties hold.

-   The map $(x_1, \ldots, x_e) \to n_1x_1 + \cdots + n_e x_e$ is a bijection from $L$ to $Ap(S,m)$.

-   If $(x_1, \ldots, x_e) \in L$, then $(y_1, \ldots, y_e) \in L$ for every $(y_1, \ldots, y_e) \in \mathbb{N}^e$ such that $y_i \le x_i$ for all $i \in \{1, \ldots, e\}$.

If $\mathbf{Z}(s)$ is the [set of factorizations](../Presentations-NS/Set-of-factorizations.qmd) for any $s \in S$, the first condition means that $|\mathbf{Z}(s) \cap L| = 1$ for all $s \in Ap(s,m)$. Moreover, it can be proven that if $x \in Ap(S,m)$ and $x - y \in S$, then $y \in Ap(S,m)$, and the second condition means that $(y_1, \ldots, y_e)$ is a factorization of an element in $Ap(S,m)$.

## Examples

$\circ$ Let $S = \langle 3, 5, 7 \rangle = \{0, 3, 5, \rightarrow \}$. Let us prove that

$$
L = \{ (0, 0, 0), (1, 0, 0), (0, 1, 0), (2, 0, 0), (1, 1, 0), (3, 0, 0), (2, 1, 0)  \},
$$

is an $L-$shape of $Ap(S,7)$. From the definitions,

$$
Ap(S, 7) := \{s \in S ~ | ~ s - 4 \not \in S\} = \{0, 8, 9, 3, 11, 5, 6 \},
$$

and

$$
\mathbf{Z}(0) = \{(0,0,0)\}, ~ \mathbf{Z}(8) = \{(1,1,0)\}, ~ \mathbf{Z}(9) = \{(3,0,0)\}, ~ \mathbf{Z}(3) = \{(1,0,0)\},
$$

$$
\mathbf{Z}(11) = \{(2,1,0)\}, ~ \mathbf{Z}(5) = \{(0,1,0)\}, ~ \mathbf{Z}(6) = \{(2,0,0)\}.
$$

Since each element has an unique factorization and $L$ is the union of all factorizations, it is concluded that $L$ is an $L-$shape of $Ap(S,7)$. In fact, is the unique $L-$shape of $Ap(S,7)$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 14, 33, 64 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 14, 33, 64);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$ minimally generated by $P = \{n_1 < n_2 < \cdots < n_e\}$, the functions `LShapes` and `LShapesOfNumericalSemigroup` return a list with all L-shapes of $Ap(S, n_e)$.

``` gap
gap> LShapes(S);
[ [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 0, 1, 0 ], [ 2, 0, 0 ], [ 1, 1, 0 ], [ 0, 2, 0 ],
      [ 0, 0, 1 ], [ 3, 0, 0 ], [ 2, 1, 0 ], [ 1, 2, 0 ], [ 0, 3, 0 ], [ 1, 0, 1 ],
      [ 0, 1, 1 ], [ 4, 0, 0 ], [ 3, 1, 0 ], [ 2, 2, 0 ], [ 1, 3, 0 ], [ 0, 4, 0 ],
      [ 2, 0, 1 ], [ 1, 1, 1 ], [ 0, 2, 1 ], [ 5, 0, 0 ], [ 0, 0, 2 ], [ 3, 2, 0 ],
      [ 2, 3, 0 ], [ 1, 4, 0 ], [ 0, 5, 0 ], [ 3, 0, 1 ], [ 2, 1, 1 ], [ 1, 2, 1 ],
      [ 0, 3, 1 ], [ 1, 0, 2 ], [ 0, 1, 2 ], [ 3, 3, 0 ], [ 2, 4, 0 ], [ 1, 5, 0 ],
      [ 0, 6, 0 ], [ 4, 0, 1 ], [ 3, 1, 1 ], [ 2, 2, 1 ], [ 1, 3, 1 ], [ 0, 4, 1 ],
      [ 1, 1, 2 ], [ 0, 2, 2 ], [ 3, 4, 0 ], [ 2, 5, 0 ], [ 0, 7, 0 ], [ 0, 0, 3 ],
      [ 3, 2, 1 ], [ 2, 3, 1 ], [ 1, 4, 1 ], [ 1, 2, 2 ], [ 0, 3, 2 ], [ 3, 5, 0 ],
      [ 0, 8, 0 ], [ 0, 1, 3 ], [ 3, 3, 1 ], [ 2, 4, 1 ], [ 1, 3, 2 ], [ 0, 4, 2 ],
      [ 0, 9, 0 ], [ 0, 2, 3 ], [ 1, 4, 2 ], [ 0, 10, 0 ] ],
  [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 0, 1, 0 ], [ 2, 0, 0 ], [ 1, 1, 0 ], [ 0, 2, 0 ],
      [ 0, 0, 1 ], [ 3, 0, 0 ], [ 2, 1, 0 ], [ 1, 2, 0 ], [ 0, 3, 0 ], [ 1, 0, 1 ],
      [ 0, 1, 1 ], [ 4, 0, 0 ], [ 3, 1, 0 ], [ 2, 2, 0 ], [ 1, 3, 0 ], [ 0, 4, 0 ],
      [ 2, 0, 1 ], [ 1, 1, 1 ], [ 0, 2, 1 ], [ 5, 0, 0 ], [ 0, 0, 2 ], [ 3, 2, 0 ],
      [ 2, 3, 0 ], [ 1, 4, 0 ], [ 0, 5, 0 ], [ 3, 0, 1 ], [ 2, 1, 1 ], [ 1, 2, 1 ],
      [ 0, 3, 1 ], [ 1, 0, 2 ], [ 0, 1, 2 ], [ 3, 3, 0 ], [ 2, 4, 0 ], [ 1, 5, 0 ],
      [ 0, 6, 0 ], [ 4, 0, 1 ], [ 3, 1, 1 ], [ 2, 2, 1 ], [ 1, 3, 1 ], [ 0, 4, 1 ],
      [ 1, 1, 2 ], [ 0, 2, 2 ], [ 3, 4, 0 ], [ 2, 5, 0 ], [ 0, 7, 0 ], [ 0, 0, 3 ],
      [ 3, 2, 1 ], [ 2, 3, 1 ], [ 1, 4, 1 ], [ 1, 2, 2 ], [ 0, 3, 2 ], [ 3, 5, 0 ],
      [ 1, 0, 3 ], [ 0, 1, 3 ], [ 3, 3, 1 ], [ 2, 4, 1 ], [ 1, 3, 2 ], [ 0, 4, 2 ],
      [ 1, 1, 3 ], [ 0, 2, 3 ], [ 1, 4, 2 ], [ 1, 2, 3 ] ],
  [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 0, 1, 0 ], [ 2, 0, 0 ], [ 1, 1, 0 ], [ 0, 2, 0 ],
      [ 0, 0, 1 ], [ 3, 0, 0 ], [ 2, 1, 0 ], [ 1, 2, 0 ], [ 0, 3, 0 ], [ 1, 0, 1 ],
      [ 0, 1, 1 ], [ 4, 0, 0 ], [ 3, 1, 0 ], [ 2, 2, 0 ], [ 1, 3, 0 ], [ 0, 4, 0 ],
      [ 2, 0, 1 ], [ 1, 1, 1 ], [ 0, 2, 1 ], [ 5, 0, 0 ], [ 0, 0, 2 ], [ 3, 2, 0 ],
      [ 2, 3, 0 ], [ 1, 4, 0 ], [ 0, 5, 0 ], [ 3, 0, 1 ], [ 2, 1, 1 ], [ 1, 2, 1 ],
      [ 0, 3, 1 ], [ 1, 0, 2 ], [ 0, 1, 2 ], [ 3, 3, 0 ], [ 2, 4, 0 ], [ 1, 5, 0 ],
      [ 0, 6, 0 ], [ 4, 0, 1 ], [ 3, 1, 1 ], [ 2, 2, 1 ], [ 1, 3, 1 ], [ 0, 4, 1 ],
      [ 1, 1, 2 ], [ 0, 2, 2 ], [ 3, 4, 0 ], [ 2, 5, 0 ], [ 5, 0, 1 ], [ 0, 0, 3 ],
      [ 3, 2, 1 ], [ 2, 3, 1 ], [ 1, 4, 1 ], [ 1, 2, 2 ], [ 0, 3, 2 ], [ 3, 5, 0 ],
      [ 1, 0, 3 ], [ 0, 1, 3 ], [ 3, 3, 1 ], [ 2, 4, 1 ], [ 1, 3, 2 ], [ 0, 4, 2 ],
      [ 1, 1, 3 ], [ 0, 2, 3 ], [ 1, 4, 2 ], [ 1, 2, 3 ] ],
  [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 0, 1, 0 ], [ 2, 0, 0 ], [ 1, 1, 0 ], [ 0, 2, 0 ],
      [ 0, 0, 1 ], [ 3, 0, 0 ], [ 2, 1, 0 ], [ 1, 2, 0 ], [ 0, 3, 0 ], [ 1, 0, 1 ],
      [ 0, 1, 1 ], [ 4, 0, 0 ], [ 3, 1, 0 ], [ 2, 2, 0 ], [ 1, 3, 0 ], [ 0, 4, 0 ],
      [ 2, 0, 1 ], [ 1, 1, 1 ], [ 0, 2, 1 ], [ 5, 0, 0 ], [ 4, 1, 0 ], [ 3, 2, 0 ],
      [ 2, 3, 0 ], [ 1, 4, 0 ], [ 0, 5, 0 ], [ 3, 0, 1 ], [ 2, 1, 1 ], [ 1, 2, 1 ],
      [ 0, 3, 1 ], [ 5, 1, 0 ], [ 4, 2, 0 ], [ 3, 3, 0 ], [ 2, 4, 0 ], [ 1, 5, 0 ],
      [ 0, 6, 0 ], [ 4, 0, 1 ], [ 3, 1, 1 ], [ 2, 2, 1 ], [ 1, 3, 1 ], [ 0, 4, 1 ],
      [ 5, 2, 0 ], [ 4, 3, 0 ], [ 3, 4, 0 ], [ 2, 5, 0 ], [ 0, 7, 0 ], [ 4, 1, 1 ],
      [ 3, 2, 1 ], [ 2, 3, 1 ], [ 1, 4, 1 ], [ 5, 3, 0 ], [ 4, 4, 0 ], [ 3, 5, 0 ],
      [ 0, 8, 0 ], [ 4, 2, 1 ], [ 3, 3, 1 ], [ 2, 4, 1 ], [ 5, 4, 0 ], [ 4, 5, 0 ],
      [ 0, 9, 0 ], [ 4, 3, 1 ], [ 5, 5, 0 ], [ 0, 10, 0 ] ],
  [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 0, 1, 0 ], [ 2, 0, 0 ], [ 1, 1, 0 ], [ 0, 2, 0 ],
      [ 0, 0, 1 ], [ 3, 0, 0 ], [ 2, 1, 0 ], [ 1, 2, 0 ], [ 0, 3, 0 ], [ 1, 0, 1 ],
      [ 0, 1, 1 ], [ 4, 0, 0 ], [ 3, 1, 0 ], [ 2, 2, 0 ], [ 1, 3, 0 ], [ 0, 4, 0 ],
      [ 2, 0, 1 ], [ 1, 1, 1 ], [ 0, 2, 1 ], [ 5, 0, 0 ], [ 4, 1, 0 ], [ 3, 2, 0 ],
      [ 2, 3, 0 ], [ 1, 4, 0 ], [ 0, 5, 0 ], [ 3, 0, 1 ], [ 2, 1, 1 ], [ 1, 2, 1 ],
      [ 0, 3, 1 ], [ 5, 1, 0 ], [ 4, 2, 0 ], [ 3, 3, 0 ], [ 2, 4, 0 ], [ 1, 5, 0 ],
      [ 0, 6, 0 ], [ 4, 0, 1 ], [ 3, 1, 1 ], [ 2, 2, 1 ], [ 1, 3, 1 ], [ 0, 4, 1 ],
      [ 5, 2, 0 ], [ 4, 3, 0 ], [ 3, 4, 0 ], [ 2, 5, 0 ], [ 5, 0, 1 ], [ 4, 1, 1 ],
      [ 3, 2, 1 ], [ 2, 3, 1 ], [ 1, 4, 1 ], [ 5, 3, 0 ], [ 4, 4, 0 ], [ 3, 5, 0 ],
      [ 5, 1, 1 ], [ 4, 2, 1 ], [ 3, 3, 1 ], [ 2, 4, 1 ], [ 5, 4, 0 ], [ 4, 5, 0 ],
      [ 5, 2, 1 ], [ 4, 3, 1 ], [ 5, 5, 0 ], [ 5, 3, 1 ] ] ]
gap> LShapesOfNumericalSemigroup(S) = LShapes(S);
true
```

## References

::: {#refs}

:::
