---
title: "Lattice path associated to a numerical semigroup"
format: html
engine: markdown
---


<!-- Geometrical-illustration-NS -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd), let $p,q$ be two coprime in $S$ and $H_{p,q} = \langle p, q \rangle$. It holds that $H_{p,q}$ is a numerical semigroup and $H_{p,q} \subseteq S$, then every [gap](Gap.qmd) of $S$ is a gap of $H_{p,q}$. If $c$ is the [conductor](Conductor.qmd) of $H_{p,q}$, every gap $g$ of $H_{p,q}$ can be written uniquely as $g = c - 1 - (ap  + bq)$, for some non-negative integers $a,b$. It is said that $(a,b)$ are the coordinates associated to $g$. Then, it is defined the lattice path of $S$ with respect to $H_{p,q}$ as the path in $\mathbb{N}^2$ such that the coordinates of the gaps of $S$ correspond exactly with the points in $\mathbb{N}^2$ that are between the path and the line $px + qy = c - 1$.

From the definition, there is no gap in the line $px + qy = c-1$.

## Examples

$\circ$ Let $S = \langle 5, 7, 9, 11, 13 \rangle = \{0, 5, 7, 9, \rightarrow\}$ and $p = 5, q = 7$. The set of gaps of $S$ is $G(S) = \{1, 2, 3, 4, 6, 8\}$. On the other hand, $H_{p,q} = \langle 5, 7 \rangle$ has conductor $C(H_{p,q})-1 = pq - p - q -1 = 23$, then $P = C(H_{p,q}) - 1 - G(S) = \{22, 21, 20, 19, 17, 15\}$ and its coordinates are $P' = \{(3,1), (0,3), (4,0), (1,2), (2,1), (3,0)\}$ ordered as in $P$. Considering the line $5x + 7y = 23$, we have the following situation.



## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle \rangle, in GAP:

```gap

```

## References

