---
title: "Left Elements"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) and $F(S)$ the [Frobenius number](Frobenius-number.qmd) of $S$. An element $s \in \mathbb{N}$ is a left element of $S$ if $s \in S$ and $s < F(S)$. The set of left elements is denoted by $N(S)$ or $L(S)$. If we include the [conductor](Conductor.qmd) in $N(S)$, they are said small elements.

The set of left elements is always non-empty, due to $0 \in N(S)$, and determines the numerical semigroup.

## Examples

$\circ$ Let $S = \langle 3, 8, 10 \rangle$. We have that $6 = 3 + 3 \in S$ and since $8,9,10 \in S$, adding $3$ to each number, we have that for $n \ge 8$, it holds $n \in S$ and $7 \not \in S$. Then, the Frobenius number is $F(S) = 7$ and the set of left elements is $N(S) = \{0, 3, 6\}$.

$\circ$ Let us consider $b \in \mathbb{N}$ an odd integer arbitrary but fixed and $S = \langle 2, b \rangle$. Note that for $n \ge b-1$, it holds $n \in S$ and $b-2 \not \in S$, thus the Frobenius number is $F(S) = b-2$ and the set of left elements is $N(S) = \{0, 2, 4, \ldots, b-3\}$, in other words, the even elements between $0$ and $b-2$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 4, 13, 17, 20 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4, 13, 17, 20);
<Numerical semigroup with 4 generators>
```

If we want to compute the left elements of $S$, the function `SmallElements` returns a list with the small elements (left elements and the conductor) of $S$.

``` gap
gap> SmallElements(S);
[ 0, 4, 8, 12, 13, 16, 17, 20, 21, 24, 25, 26, 28, 29, 30, 32, 33, 34, 36 ]
```

Obviously, the conductor is the greatest element of the list, in this case, $C(S) = 36$. Another way to know the left elements of $S$ is from the function `Gaps`, which returns the [gaps](Gap.qmd) of $S$. If $G(S)$ is the set of gaps, therefore $N(S) = \{0, 1, 2, \ldots, F(S)-1\} \setminus G(S)$.

``` gap
gap> Gaps(S);
[ 1, 2, 3, 5, 6, 7, 9, 10, 11, 14, 15, 18, 19, 22, 23, 27, 31, 35 ]
```


$\diamond$ Given a list of non-negative integers, the function `NumericalSemigroupBySmallElements` generates a numerical semigroup determined by the list if it is possible, which is considered as the list of small elements of the numerical semigroup.


```gap
gap> l := [0,5,10,11,14,15,16,19,20,21,22,24];
[ 0, 5, 10, 11, 14, 15, 16, 19, 20, 21, 22, 24 ]
gap> S := NumericalSemigroupBySmallElements(l);
<Numerical semigroup>
gap> MinimalGenerators(S);
[ 5, 11, 14 ]
```
The function `MinimalGenerators` returns the [minimal set of generators](Minimal-set-of-generators.qmd) of $S$. It is obtained that $S = \langle 5, 11, 14 \rangle$ and $N(S) = \{0, 5, 10, 11, 14, 15, 16, 19, 20, 21, 22\}$.


The function `RepresentsSmallElementsOfNumericalSemigroup` returns true or false depending on whether a given list may represent the small elements of a numerical semigroup.

```gap
gap> RepresentsSmallElementsOfNumericalSemigroup(l);
true
```



## References

::: {#refs}

:::

