---
title: "Maximal embedding dimension closure"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @JMDA, @CMCNS
---

<!-- Computation MED closure of a NS -->

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) and let $\mathcal{O}(S)$ be the set of [oversemigroups](Oversemigroup.qmd) of $S$. It is defined the maximal embedding dimension closure (or MED closure) of $S$, denoted by $MED(S)$, as the smallest [MED numerical semigroup](../Families-NS/NS-maximal-embedding-dimension.qmd) containing $S$.

## Examples

$\circ$ Let $S = \langle 4, 7, 10 \rangle$. The maximal embedding dimension oversemigroups of $S$ are

$$
S_1 = \mathbb{N}, ~ S_2 = \langle 2,3 \rangle, ~ S_3 = \langle 2, 5 \rangle, ~ S_4 = \langle 2, 7 \rangle, ~ S_5 = \langle 3, 4, 5 \rangle,
$$

$$
S_6 = \langle 4, 5, 6, 7 \rangle, ~ S_7 = \langle 4, 6, 7, 9 \rangle, ~ S_8 = \langle 4,7,9,10 \rangle, ~ S_9 = \langle 4, 7, 10, 13 \rangle.
$$

Therefore, the MED closure of $S$ is

$$
MED(S) = \bigcap_{i = 1}^9 S_i = \langle 4, 7, 10, 13 \rangle = \{0, 4, 7, 8, 10, \rightarrow \}.
$$

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 8, 10, 12, 15\rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(8, 10, 12, 15);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$, the function `MEDClosure` returns the MED closure of $S$.

``` gap
gap> T := MEDClosure(S);
<Numerical semigroup>
gap> MinimalGenerators(T);
[ 8, 10, 12, 14, 15, 17, 19, 21 ]
```

The function `MinimalGenerators` returns the [minimal set of generators](Minimal-set-of-generators.qmd) of the given numerical semigroup. Therefore,

$$
MED(S) = \langle 8, 10, 12, 14, 15, 17, 19, 21 \rangle.
$$

## References

::: {#refs}

:::
