---
title: "Maximal embedding dimension system of generators"
format: html
engine: markdown
---

<!--  -->

## Definition

Let $S$ be a [maximal embedding dimension](../Families-NS/NS-maximal-embedding-dimension.qmd) [numerical semigroup](Numerical-semigroup.qmd) and $M = \{m_1, \ldots, m_k\}$ a set of positive integers with $gcd(M) = 1$ and $m_1 < \ldots < m_k$. It is said that $M$ is a maximal embedding dimension system of generators of $S$ (or a MED system of generators of $S$) if the [MED closure](MED-closure.qmd) of $M$ is $S$.

It can be proven that for any MED numerical semigroup $S$, there exists a finite and unique minimal MED system of generators $M$ such that the MED closure of $M$ is $S$. Moreover, $M$ is a subset of the [minimal set of generators](Minimal-set-of-generators.qmd) of $S$. This definition is a particular case of [V-monoids generated by a subset](../Varieties-NS/V-monoid-generated.qmd).

## Examples

$\circ$ Let $S = \langle 4, 6, 7, 9 \rangle$. Since $e(S) = m(S) = 4$, where $e(S)$ is the [embedding dimension](Embedding-dimension.qmd) and $m(S)$ is the [multiplicity](Multiplicity.qmd) of $S$ respectively, we have that $S$ has maximal embedding dimension. From the condition $gcd(M) = 1$, the candidates to be the MED system of generators of $S$ are

$$
M_1 = \{4, 7\}, ~~ M_2 = \{4, 9\}, ~~ M_3 = \{6, 7\}, ~~ M_4 = \{7,9\},
$$

$$
M_5 = \{4, 6, 7\}, ~~ M_6 = \{4, 6, 9\}, ~~ M_7 = \{6, 7, 9\}, ~~ M_8 = \{4, 6, 7, 9\}.
$$

If $S$ is the MED closure of $M_j$ with $j \in \{1, \ldots, 8\}$, then $\min M_j = m(S) = 4$, obtaining that $M_1, M_2, M_5, M_6, M_8$ are the only possibilities. From this, it is deduced that the MED system of generators is $M_5 = \{4,6,7\}$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 6, 9, 10, 11, 13, 14 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(6, 9, 10, 11, 13, 14);
<Numerical semigroup with 6 generators>
```

Given a numerical semigroup $S$, the function `IsMED` returns true if $S$ is a MED numerical semigroup and false otherwise.

``` gap
gap> IsMED(S);
true
```

Moreover, the function `MinimalMEDGeneratingSystemOfMEDNumericalSemigroup` returns the MED system of generators of $S$.

``` gap
gap> MinimalMEDGeneratingSystemOfMEDNumericalSemigroup(S);
[ 6, 9, 10, 11 ]
```

## References
