---
title: "Oversemigroup"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd). It is said that $T$ is a oversemigroup of $S$ if $T$ is a numerical semigroup and $S \subseteq T$. The set of oversemigroups of $S$ is denoted by $\mathcal{O}(S)$.

The set $\mathcal{O}(S)$ is non-empty and finite for every numerical semigroup, since $S \in \mathcal{O}(S)$ and $|\mathbb{N} \setminus S|$ is finite.

## Examples

$\circ$ Let $S = \langle 4, 5, 6 \rangle = \{ 0, 4, 5, 6, 8, \rightarrow\}$. The [gaps](Gap.qmd) of $S$ are $G(S) = \{1, 2, 3, 7\}$, so to compute the oversemigroups we have to add gaps to $S$ and check if it is in fact a numerical semigroup.

-   0 gaps: we have $S \subseteq S$ so $S$ is trivially a oversemigroup of $S$.

-   1 gap: the candidates are $T_{1,1} = S \cup \{1\}, T_{1,2} = S \cup \{2\}, T_{1,3} = S \cup \{3\}, T_{1,4} = S \cup \{7\}$. It is easy to check that $T_4$ is the only numerical semigroup.

-   2 gaps: in this case the oversemigroups are $T_{2,1} = S \cup \{2, 7\}, T_{2,2} = S \cup \{3, 7\}$.

-   3 gaps: the only oversemigroup is $T_{3,1} = S \cup \{2, 3, 7\}$.

-   4 gaps: we have the oversemigroup $T_{4,1} = \mathbb{N}$.

To sum up, $\mathcal{O}(S) = \{S, S \cup \{7\}, S \cup \{2, 7\}, S \cup \{3, 7\}, S \cup \{2, 3, 7\}, \mathbb{N}\}$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 2, 5 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(2, 5);
<Numerical semigroup with 2 generators>
```

The functions `Oversemigroups` and `OverSemigroupsNumericalSemigroup` returns the set of oversemigroups.

``` gap
gap> OverSemigroups(S);
[ <The numerical semigroup N>, <Numerical semigroup with 2 generators>, <Numerical semigroup with 2 generators> ]
gap> OverSemigroups(S) = OverSemigroupsNumericalSemigroup(S);
true
```

The code `List(List_NS, l -> Function(l));` returns a list where it has applied `Function` to every element in $List\_NS$. For example, we can see the oversemigroups of $S$ by its [left elements](Left-elements.qmd) and its [conductor](Conductor.qmd),

``` gap
gap> List(OverSemigroups(S), l -> SmallElements(l));
[ [ 0 ], [ 0, 2 ], [ 0, 2, 4 ] ]
```

or by its gaps,

``` gap
gap> List(OverSemigroups(S), l -> Gaps(l));
[ [  ], [ 1 ], [ 1, 3 ] ]
```

It is concluded that $\mathcal{O}(S) = \{S, T, \mathbb{N}\}$, where $T = \{0, 2, \rightarrow\}$.

$\diamond$ Let $S = \langle 4,5,6 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4,5,6);
<Numerical semigroup with 3 generators>
```

Given a numerical semigroup $S$, the function `DotOverSemigroupsNumericalSemigroup` returns the Hasse diagram (in dot) of oversemigroups of $S$.

``` gap
gap> h := DotOverSemigroupsNumericalSemigroup(S);;
gap> Print(DotOverSemigroupsNumericalSemigroup(S));
digraph  NSGraph{rankdir = TB; edge[dir=back];
1 [label="〈 1 〉", style=filled];
2 [label="〈 2, 3 〉", style=filled];
3 [label="〈 2, 5 〉", style=filled];
4 [label="〈 3, 4, 5 〉", style=filled];
5 [label="〈 4, 5, 6, 7 〉"];
6 [label="〈 4, 5, 6 〉", style=filled];
1 -> 2;
2 -> 3;
2 -> 4;
3 -> 5;
4 -> 5;
5 -> 6;
}
```

The obtained graph is as follows.

::: {style="text-align:center;"}
```{dot}
// | fig-width: 65%
// | fig-height: 300px
digraph  NSGraph{rankdir = TB; edge[dir=back];
1 [label="〈 1 〉", style=filled];
2 [label="〈 2, 3 〉", style=filled];
3 [label="〈 2, 5 〉", style=filled];
4 [label="〈 3, 4, 5 〉", style=filled];
5 [label="〈 4, 5, 6, 7 〉"];
6 [label="〈 4, 5, 6 〉", style=filled];
1 -> 2;
2 -> 3;
2 -> 4;
3 -> 5;
4 -> 5;
5 -> 6;
}

```
:::

The nodes with grey background are irreducible numerical semigroups.

## References

::: {#refs}

:::