---
title: "RF-matrix of a pseudo-Frobenius number"
format: html
engine: markdown
---

<!-- Moscariello, A., On the type of an almost Gorenstein monomial curve, J. Algebra, 456 (2016), 266--277. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) [minimally generated](Minimal-set-of-generators.qmd) by $P(S) = \{n_1, \ldots, n_e\}$ with $n_1 < \cdots < n_e$ and let $f \in PF(S)$ a [pseudo-Frobenius number](Pseudo-Frobenius-number.qmd). By definition of pseudo-Frobenius number, it holds that $f + n_i \in S$ for all $i \in \{1, \ldots, e\}$. Then, it is said that a matrix $A \in \mathcal{M}_{e \times e}(\mathbb{Z})$ is a $RF-$matrix of $f$ in $S$ if the $i-$th row is a [factorization](../Presentations-NS/Set-of-factorizations.qmd) of $f + n_i$ in $S$ with $a_{i,i} = -1$ for all $i \in \{1, \ldots, e\}$.

## Examples

$\circ$ Let $S = \langle 5, 7, 13 \rangle = \{0, 5, 7, 10, 12, 13, 14, 15, 17, \rightarrow\}$ and $f = 8 \in PF(S)$. We have that $8 + 5 = 13 = 0 \cdot 5 + 0 \cdot 7 + 1 \cdot 13$, $8 + 7 = 15 = 3 \cdot 5 + 0 \cdot 7 + 0 \cdot 13$, $8 + 13 = 21 = 0 \cdot 5 + 3 \cdot 7 + 0 \cdot 13$ and these are the unique factorizations of $13, 15$ and $20$, respectively. Then, the unique $RF-$matrix of $f = 8$ in $S$ is

$$
A = \begin{pmatrix}
  -1 & 0 & 1 \\
  3 & -1 & 0 \\
  0 & 3 & -1 \\
\end{pmatrix}.
$$

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 31, 35, 50, 87, 111, 121, 130 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(31, 35, 50, 87, 111, 121, 130);
<Numerical semigroup with 7 generators>
```

Given a numerical semigroup $S$ and a pseudo-Frobenius number of $S$, the function `RFMatrices` returns a list with all the $RF-$matrices of $f$ in $S$. The function `PseudoFrobenius` computes the set of pseudo-Frobenius numbers of $S$.

``` gap
gap> F := PseudoFrobenius(S);
[ 115, 169, 176, 179, 189, 195 ]
gap> RFMatrices(115, S);
[ [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 6, 0, 1, 0, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 6, 0, 1, 0, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 1, 3, 2, 0, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 1, 3, 2, 0, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 2, 0, 0, 2, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 2, 4, 0, -1, 0, 0, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 2, 0, 0, 2, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 6, 0, 1, 0, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 6, 0, 1, 0, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 1, 3, 2, 0, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 1, 3, 2, 0, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 2, 0, 0, 2, 0, -1, 0 ], [ 0, 7, 0, 0, 0, 0, -1 ] ],
  [ [ -1, 1, 0, 0, 1, 0, 0 ], [ 0, -1, 3, 0, 0, 0, 0 ], [ 0, 1, -1, 0, 0, 0, 1 ],
      [ 1, 0, 1, -1, 0, 1, 0 ], [ 0, 3, 0, 0, -1, 1, 0 ],
      [ 2, 0, 0, 2, 0, -1, 0 ], [ 4, 0, 0, 0, 0, 1, -1 ] ] ]
```

## References
