---
title: "Type"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](Numerical-semigroup.qmd) and let $PF(S)$ be the set of [pseudo-Frobenius numbers](Pseudo-Frobenius-number.qmd) of $S$. The type of $S$ is defined as the cardinal of $PF(S)$.

## Examples

$\circ$ Let $S = \langle 4, 6, 9, 13 \rangle = \{0, 4, 6, 8, 9, 10, 12, \rightarrow \}$, let us compute the pseudo-Frobenius numbers of $S$. The positive integers that do not belong to $S$ are $\mathbb{N} \setminus S = \{1,2,3,5,7,11\}$ and as $4 \in S$, the candidates for pseudo-Frobenius numbers belongs to the set $\{-4, -3, -2, -1, 1,2,3,5,7,11 \}$. Checking the condition of pseudo-Frobenius number on every candidate, it is conclude that $PF(S) = \{11\}$ and $t(S) = 1$.

$\circ$ The type of a numerical semigroup is $1$ if, and only if, $2g(S) = C(S)$, where $g(S)$ is the [genus](Genus.qmd) of $S$ and $C(S)$ the [conductor](Conductor.qmd) of $S$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 7, 9, 10, 15, 20 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(7, 9, 10, 15, 20);
<Numerical semigroup with 5 generators>
```

To compute the type of $S$ we can apply the function `Type` or `TypeOfNumericalSemigroup`.

``` gap
gap> Type(S);
4
gap> Type(S) = TypeOfNumericalSemigroup(S);
true
```

Applying the function `PseudoFrobenius`, we are able to obtain explicitly the pseudo-Frobenius numbers of $S$.

``` gap
gap> PseudoFrobenius(S);
[ 8, 11, 12, 13 ]
```

## References
