---
title: "Bézout sequence"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ns, @JMDA
---

<!-- Definición de Num. Sem. -->

## Definition

Let us consider a sequence of fractions $\frac{a_1}{b_1} < \frac{a_2}{b_2} < \cdots < \frac{a_p}{b_p}$. Then, it is said that the sequence of fractions is a Bézout sequence if $a_1, \ldots, a_p, b_1, \ldots, b_p$ are positive integers and $a_{i+1}b_i - b_{i+1}a_i = 1$ for all $i \in \{1, \ldots, p-1\}$. It is defined the length of the Bézout sequence as the integer $p$ and the fractions $\frac{a_1}{b_1}, \frac{a_p}{b_p}$ are defined as the ends of the Bézout sequence.

## Examples

<!-- Ejemplo de Num. Sem. -->

$\circ$ Let

$$
\frac{131}{50} < \frac{76}{29} < \frac{21}{8} < \frac{8}{3}, 
$$

be a sequence of fractions. We have $a_1 = 131, a_2 = 76, a_3 = 21, a_4 = 8$ and $b_1 = 50, b_2 = 29, b_3 = 8, b_4 = 3$, and $76 \cdot 50 - 131 \cdot 29 = 21 \cdot 29 - 76 \cdot 8 = 8 \cdot 8 - 21 \cdot 3 = 1$. Therefore, is a Bézout sequence with length $p = 4$ and ends $\frac{131}{50}, \frac{8}{3}$.

$\circ$ Let

$$
\frac{w}{10} < \frac{x}{9} < \frac{y}{8} < \frac{z}{7},
$$

be a sequence of fractions. Then, is a Bézout sequence if, and only if, $w \equiv 1 ~ (mod ~ 10)$, $w > 0$ and $x,y,z$ are determined by the equations

$$
10x - 9w = 1, ~~~ 9y - 8x = 1, ~~~ 8z - 7y = 1,
$$

Indeed, note that the equations are the condition of Bézout sequence and can be rewritten as

$$
x = \frac{9w + 1}{10}, ~~~ y = \frac{36w + 9}{45}, ~~~ z = \frac{252w+108}{360}.
$$

Then, the sequence of fractions is a Bézout sequence if, and only if, $w > 0$ and

$$
\begin{cases}
  9w + 1 \equiv 0 ~ (mod ~ 10), \\
  36w + 9 \equiv 0 ~ (mod ~ 45), \\
  252w + 108 \equiv 0 ~ (mod ~ 360).
\end{cases}
$$

Simplifying the system of congruences, it turns out that the set of solutions are those $w \in \mathbb{Z}$ such that $w \equiv 1 ~ (mod ~ 10)$, where it is deduced the result.

## Examples with GAP

<!-- Ejemplo de Num. Sem. -->

$\diamond$ Let $\frac{5}{3} < \frac{12}{7} < \frac{7}{4} < \frac{9}{5}$. Given a list in rational numbers $I$, the function `BezoutSequence` returns true or false depending on whether the list $I$ is a Bézout sequence or not, respectively.

``` gap
gap> IsBezoutSequence([ 5/3, 12/7, 7/4, 9/5 ]);
true
```

Then, the sequence is a Bézout sequence. Moreover, given two rational numbers $x,y$, the function `BezoutSequence` returns a Bézout sequence with ends $x,y$.

``` gap
gap> BezoutSequence(12/5, 39/10);
[ 12/5, 5/2, 3, 7/2, 11/3, 15/4, 19/5, 23/6, 27/7, 31/8, 35/9,
  39/10 ]
```

## References

::: {#refs}

:::
