---
title: "Modulus of a proportionally modular Diophantine inequality"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $a, b$ and $c$ be positive integers and let $ax ~ (mod ~ b) \le cx$ be a [proportionally modular Diophantine inequality](Prop-mod-Diophantine-ineq.qmd). It is defined the modulus of the proportionally modular Diophantine inequality as the integer $b$. The integer $a$ is defined as the [factor](Factor-prop-mod-Diophantine-ineq.qmd) and $c$ is defined as the [proportion](Proportion-prop-mod-Diophantine-ineq.qmd) of the proportionally modular Diophantine inequality.

## Examples

$\circ$ Let $14x ~ (mod ~ 52) \le 7x$. Then, the factor of the proportionally modular Diophantine inequality is $a = 14$, the modulus is $b = 52$ and the proportion is $c = 7$. It can be proven that the set of solutions is $S(14, 52, 7) = \{0, 4, \rightarrow\}$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $a, b, c$ positive integers. Te function `ProportionallyModularNumericalSemigroup` returns the numerical semigroup generated by the proportionally modular Diophantine inequality $ax ~ (mod ~ b) \le cx$.

``` gap
gap> a := 14;
14
gap> b := 57;
57
gap> c := 6;
6
gap> S := ProportionallyModularNumericalSemigroup(a,b,c);
<Proportionally modular numerical semigroup satisfying 14x mod 57 <= 6x >
```

The function `SmallElements` returns a list with the [left elements](../Basic-concepts/Left-elements.qmd) and the [conductor](../Basic-concepts/Conductor.qmd) of the numerical semigroup.

``` gap
gap> SmallElements(S);
[ 0, 5, 6, 7, 9 ]
```

Therefore, the set of solutions of $14x ~ (mod ~ 57) \le 6x$ is $S = \{0, 5, 6, 7, 9, \rightarrow\}$.

$\diamond$ Let $a, b$ positive integers. The function `ModularNumericalSemigroup` returns the numerical semigroup generated by the [modular Diophantine inequality](Mod-Diophantine-ineq.qmd) $ax ~ (mod ~ b) \le x$.

``` gap
gap> a := 6;
6
gap> b := 19;
19
gap> S := ModularNumericalSemigroup(a,b);
<Modular numerical semigroup satisfying 6x mod 19 <= x >
```

If we use the function `SmallElements`,

``` gap
gap> SmallElements(S);
[ 0, 7, 10, 11, 13 ]
```

Then, the set of solutions of $6x ~ (mod ~ 19) \le x$ is $S = \{0, 7, 10, 11, 13, \rightarrow \}$.

## References
