---
title: "Period of a subadditive function"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $\mathbb{Q}_0^+$ denote the set of non-negative rational numbers, let $f : \mathbb{N} \to \mathbb{Q}_0^+$ be a [subadditive function](Subadditive-function.qmd) and $m \in \mathbb{N} \setminus \{0\}$. It is said that $f$ has period $m$ if for all $x \in \mathbb{N}$, it holds $f(x + m) = f(x)$. It is denoted by $\mathscr{JF}_m$ the set of $m-$periodic subadditive functions.

Given a subadditive function $f$, the set

$$
M(f) = \{x \in \mathbb{N} ~ | ~ f(x) \le x\},
$$

is a submonoid of $\mathbb{N}$. Moreover, if $f$ has period $m \in \mathbb{N} \setminus \{0\}$, it can be proven that $M(f)$ is a numerical semigroup.

## Examples

$\circ$ Let $f: \mathbb{N} \to \mathbb{Q}_0^+$ such that $f(0) = 0, f(1) = 7, f(2) = 4$ and for all $x \in \mathbb{N}$ such that $x \ge 3$, $f(x) = f(x ~ mod ~3 )$. Let us prove that $f$ is a $3-$periodic subadditive function. Let $x, y \in \mathbb{N}$, we divide in two cases.

-   $x = y$: we have that $f(1 + 1) = f(2) = 4 < 14 = f(1) + f(1)$ and $f(2 + 2) = f(4) = f(1) = 7 < 8 = f(2) + f(2)$. If $x \equiv 1 ~ (mod ~ 3)$, $f(2x) = f(2) < f(1) + f(1) = f(x) + f(x)$ and if $x \equiv 2 ~ (mod ~ 3)$, $f(2x) = f(4) < f(2) + f(2) = f(x) + f(x)$.

-   $x \equiv 1 ~ (mod ~ 3), y \equiv 2 ~ (mod ~ 3)$, then $f(x + y) = f(0) = 0 < f(x) + f(y)$.

In conclusion. $f$ is a $3-$periodic subadditive function.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $f$ be a periodic subadditive function with period $m$. Given a list of images of the integers from $1$ to $m$, the function `NumericalSemigroupBySubAdditiveFunction` returns the numerical semigroup $M(f)$ if it is possible (that means, if the list generates a subadditive function). The image of $m$ has to be $0$.

``` gap
gap> S := NumericalSemigroupBySubAdditiveFunction([6, 5, 3, 0]);
<Numerical semigroup>
```

$S$ is the numerical semigroup of the subadditive function $f$ such that $f(0) = 0, f(1) = 6, f(2) = 5, f(3) = 3$ and period $m = 4$. The function `SmallElements` returns a list with the [left elements](../Basic-concepts/Left-elements.qmd) and the [conductor](../Basic-concepts/Conductor.qmd) of the numerical semigroup.

``` gap
gap> SmallElements(S);
[ 0, 3, 4, 6 ]
```

To sum up, the numerical semigroup generated by $f$ is $S = M(f) = \{0, 3, 4, 6, \rightarrow\}$.

## References
