---
title: "Weight of a modular Diophantine inequality"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $a,b$ be positive integers such that $0 < a < b$ and let $ax ~ (mod ~ b) \le x$ be the [modular Diophantine inequality](Mod-Diophantine-ineq.qmd). It is defined the weight of the modular Diophantine inequality, denoted by $w(a,b)$, as $w(a,b) = b - gcd(a, b) - gcd(a-1, b)$.

## Examples

$\circ$ Let $a = 15, b = 24$ and the modular Diophantine inequality $15x ~ (mod ~ 24)$. We have, $gcd(15, 24) = 3$ and $gcd(14, 24) = 2$. Then, the weight is

$$
w(a,b) = b - gcd(a,b) - gcd(a-1, b) = 24 - 3 - 2 = 19.
$$

## Examples with GAP

Nowadays, there are no functions in package NumericalSgps related to weight of a modular Diophantine inequality. However, given two positive integers $a,b$, the following function returns the weight of the modular Diophantine inequality $a'x ~ (mod ~ b) \le x$, where $a' = a ~ (mod ~ b)$.

```gap
gap> WeightModDiophantineIneq := function(a,b)
>       local c;
>       c := a mod b;
>       return b - Gcd(c,b) - Gcd(c-1,b);
> end;
function( a, b ) ... end
```


$\diamond$ Let $a = 12, b = 27$ and the modular Diophantine inequality $ax ~ (mod ~ b) \le x$. If we use the function defined above,

```gap
gap> WeightModDiophantineIneq(12, 27);
23
```

Then, the weight of the modular Diophantine inequality is $w(12,27) = 23$.



## References








