---
title: "Arf semigroup"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is said that $S$ is Arf if every [integrally closed](../Ideals-NS/Integrally-closed-ideal.qmd) [proper ideal](../Ideals-NS/Proper-ideal.qmd) of $S$ is [stable](../Ideals-NS/Stable-ideal.qmd). It can be proven that a numerical semigroup $S$ is Arf if, and only if, for any $s,t \in S$ with $s \le t$, it holds $2t - s \in S$.

## Examples

$\circ$ Let $S = \langle 5, 7, 9 \rangle = \{0, 5, 7, 9, 10, 12, 14, \rightarrow \}$, $I = \{9, 10, 12, 14\}$ and $E = I + S$. It is easy to prove that $E = (9 + \mathbb{N}) \cap S = S(9)$. Then, $E$ is integrally closed, but $r(E) = 2$, since

$$
2E = E + E = \{18, \rightarrow \} \ne \{18, 19, 21, 23, \rightarrow \} = m(E) + E,
$$

and

$$
3E = E + (E + E) = \{27, \rightarrow \} = m(E) + 2E.
$$

Therefore, $E$ is integrally closed but not stable. Thus, $S$ is not an Arf semigroup. Let us also note that $2 \cdot 9 - 7 = 11 \not \in S$, but $7,9 \in S$.

$\circ$ Let $S = \langle 3, 5, 7 \rangle = \{0, 3, 5, \rightarrow \}$, let's prove that for any $s,t \in S$ with $s \le t$, it holds $2t - s \in S$. The [conductor](../Basic-concepts/Conductor.qmd) of $S$ is $C(S) = 5$, we divide into cases:

-   If $t < C(S)$, it must be $t = 0$ or $t = 3$ and the property holds easily.

-   If $t \ge C(S)$, let $s \in S$ with $s \le t$. Then, $2t - s = t + (t-s) \ge t \ge C(S)$ and $2t - s \in S$.

Therefore, $S$ is an Arf semigroup. In fact, we have proven that $S$ is Arf if, and only if, for any $s \in S$ and $t \in N(S)$ with $s \le t$, where $N(S)$ denotes the set of [left elements](../Basic-concepts/Left-elements.qmd) of $S$, it holds $2t - s \in S$.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 20, 24, 45, 66 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(20, 24, 45, 66);
<Numerical semigroup with 4 generators>
```

The function `IsArf` returns true or false depending on whether a numerical semigroup is Arf or not.

``` gap
gap> IsArf(S);
false
```

$\diamond$ There are several functions related to how many Arf numerical semigroups satisfy a certain condition.

-   Condition on [Frobenius number](../Basic-concepts/Frobenius-number.qmd): the function `ArfNumericalSemigroupsWithFrobeniusNumber` returns the Arf numerical semigroups with Frobenius number equals to a given number.

``` gap
gap> Length(ArfNumericalSemigroupsWithFrobeniusNumber(10));
9
```

This function is extended with the function `ArfNumericalSemigroupsWithFrobeniusNumberUpTo`, which returns the Arf numerical semigroups with Frobenius number less than or equal to a given number.

``` gap
gap> Length(ArfNumericalSemigroupsWithFrobeniusNumberUpTo(10));
46
```

-   Condition on [genus](../Basic-concepts/Genus.qmd): the function `ArfNumericalSemigroupsWithGenus` returns the Arf numerical semigroups with genus equals to a given number.

``` gap
gap> Length(ArfNumericalSemigroupsWithGenus(12));
31
```

This function is extended with the function `ArfNumericalSemigroupsWithGenusUpTo`, which returns the Arf numerical semigroups with genus less than or equal to a given number.

``` gap
gap> Length(ArfNumericalSemigroupsWithGenusUpTo(12));
143
```

-   Condition on Frobenius number and genus: The function `ArfNumericalSemigroupsWithGenusAndFrobeniusNumber` returns the Arf numerical semigroups with genus and Frobenius number both fixed. The first parameter is the genus and the next one is the Frobenius number.

``` gap
gap> Length(ArfNumericalSemigroupsWithGenusAndFrobeniusNumber(12,15));
6
```

## References
