---
title: "Arf-irreducible"
format: html
engine: markdown
---

<!--  -->

## Definition

Let $S$ be an [Arf](Arf-semigroup.qmd) [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is said that $S$ is Arf-irreducible if $S$ is irreducible in the [Frobenius variety](../Varieties-NS/Frobenius-variety.qmd) of Arf numerical semigroups.

## Examples

$\circ$ Let us consider the Arf semigroup $S = \langle 2, 9 \rangle$. The Arf oversemigroups of $S$, other than $S$ and $\mathbb{N}$, are

$$
S_1 = \langle 2, 3 \rangle, ~~ S_2 = \langle 2, 5 \rangle, ~~ S_3 = \langle 2, 9 \rangle.
$$ 

Since $S_3 \subseteq S_2 \subseteq S_1$, all the intersections generates $S_1, S_2$ or $S_3$. Therefore, $S$ is Arf-irreducible.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 9, 21, 22, 23, 24, 25, 26, 28, 29 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(9, 21, 22, 23, 24, 25, 26, 28, 29);
<Numerical semigroup with 9 generators>
```

Given a numerical semigroup $S$, the function `IsArf` returns true if $S$ is an Arf semigroup and false otherwise.

``` gap
gap> IsArf(S);
true
```

Given a numerical semigroup $S$, the function `IsArfIrreducible` returns true if $S$ is Arf-irreducible and false otherwise.

``` gap
gap> IsArfIrreducible(S);
false
```

In order to obtain the decomposition into Arf-irreducible, we can apply the function `DecomposeIntoArfIrreducibles`.

``` gap
gap> A := DecomposeIntoArfIrreducibles(S);
[ <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 9 generators> ]
gap> List(A, l -> MinimalGenerators(l));
[ [ 3, 22, 23 ], [ 9, 16, 20, 21, 22, 23, 24, 26, 28 ] ]
```

The function `MinimalGenerators` returns the [minimal set of generators](../Basic-concepts/Minimal-set-of-generators.qmd) of the given numerical semigroup. Therefore, the decomposition of $S$ into Arf-irreducible is

$$
S = \langle 3, 22, 23 \rangle \cap \langle 9, 16, 20, 21, 22, 23, 24, 26, 28  \rangle.
$$

## References
