---
title: "Numerical semigroup with Apéry set of unique expression"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) [minimally generated](../Basic-concepts/Minimal-set-of-generators.qmd) by $\{n_1, \ldots, n_e\}$ with $n_1 < n_2 < \cdots < n_e$. It is said that $S$ is a numerical semigroup with Apéry set of unique expression if every element in $Ap(S, n_1)$ has unique expression, that is, $|\mathbf{Z}(s)| = 1$ for all $s \in Ap(S, n_1)$, where $\mathbf{Z}(s)$ is the [set of factorizations of s](../Presentations-NS/Set-of-factorizations.qmd).

## Examples

$\circ$ Let $S = \langle 4, 6, 11 \rangle$. It is easy to check that $Ap(S, 4) \subseteq \{0, 4, 6, 8, 10, 11, 12, 14, 15, 16, 17\}$ and $Ap(S, 4) = \{0, 6, 11, 17\}$. Since $s = 6$ and $s = 11$ are minimal generators, both have unique expression. For $s = 17$, we have the unique expression $17 = 6 + 11$. Therefore, $S$ is a numerical semigroup with Apéry set of unique expression.

## Examples with GAP

Nowadays, there are no functions in package NumericalSgps related to numerical semigroup with Apéry set of unique expression. However, given a numerical semigroup $S$, the following function returns true if $S$ is a numerical semigroup with Apéry set of unique expression and false otherwise.

``` gap
gap> IsAperySetOfUniqueExpression := function(S)
>       if not IsNumericalSemigroup(S) then
>               Error("The argument must be a Numerical Semigroup");
>       fi;
>       for w in AperyList(S) do
>               if Length(Factorizations(w,S)) > 1 then
>                       return false;
>               fi;
>       od;
>       return true;
> end;
function( S ) ... end
```

$\diamond$ Let $S = \langle 13,14,15 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(13,14,15);
<Numerical semigroup with 3 generators>
```

The Apéry set of $S$ is $Ap(S,13) = \{0,4,5\}$ and every element (not taking into account $w = 0$) has unique expression, since there are minimal generators.

``` gap
gap> IsAperySetOfUniqueExpression(S);
true
```

$\diamond$ If we consider $S = \langle 17, 22, 24, 40 \rangle$,

``` gap
gap> S := NumericalSemigroup(17, 22, 24, 40);
<Numerical semigroup with 4 generators>
gap> IsAperySetOfUniqueExpression(S);
false
```

For example, $88 \in Ap(S, 17)$ and $88 = 4 \cdot 22 = 2 \cdot 24 + 1 \cdot 40$.

## References

<!-- https://docs.gap-system.org/doc/tut/chap0_mj.html#contents -->
