---
title: "Complete intersection numerical semigroup"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is said that $S$ is a complete intersection if the cardinality of any minimal [presentation](../Presentations-NS/Presentation-NS.qmd) of $S$ is equal to $e(S) - 1$, where $e(S)$ denotes the [embedding dimension](../Basic-concepts/Embedding-dimension.qmd) of $S$.

It can be proven that every numerical semigroup is finite presented, that every minimal presentation has the same cardinal and that every presentations $\rho$ of $S$ has cardinal $|\rho| \ge e(S) - 1$.

## Examples

$\circ$ Let us consider $a,b \in \mathbb{N} \setminus \{0,1\}$ with $gcd(a,b) = 1$ and $S = \langle a, b \rangle$. A minimal presentation of $S$ is $\rho = \{(bx_1, ax_2)\}$, whose cardinal is $1 = e(S) - 1$. Then, any numerical semigroup with embedding dimension two is a complete intersection.

$\circ$ Given a numerical semigroup with embedding dimension three, the concepts of [symmetric](../Families-NS/NS-symmetric.qmd), [free](../Families-NS/NS-free.qmd) and complete intersection are equivalent.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 22, 24, 51, 115, 122 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(22, 24, 51, 115, 122);
<Numerical semigroup with 5 generators>
```

Given a numerical semigroup, the function `IsCompleteIntersection` returns true or false depending on whether a numerical semigroup is a complete intersection or not.

``` gap
gap> IsCompleteIntersection(S);
false
```

The function `MinimalPresentation` returns a minimal presentation of a given numerical semigroup. On the other hand, the function `EmbeddingDimension` returns the embedding dimension.

``` gap
brk_3> Length(MinimalPresentation(S));
11
brk_3> EmbeddingDimension(S)-1;
4
```

$\diamond$ Given an integer $z \in \mathbb{Z}$, the function `CompleteIntersectionNumericalSemigroupsWithFrobeniusNumber` returns a list with all numerical semigroups that are a complete intersection with [Frobenius number](../Basic-concepts/Frobenius-number.qmd) $z$.

``` gap
gap> Length(CompleteIntersectionNumericalSemigroupsWithFrobeniusNumber(21));
5
```

The code `List(List_NS, l -> Function(l));` returns a list where it has applied `Function` to every element in $List\_NS$, for example, we can see the numerical semigroups with complete intersection and Frobenius number $f = 21$ by its [minimal generators](../Basic-concepts/Minimal-set-of-generators.qmd).

``` gap
gap> Li := CompleteIntersectionNumericalSemigroupsWithFrobeniusNumber(21);
[ <Numerical semigroup with 2 generators>,
  <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators>,
  <Numerical semigroup with 3 generators> ]
gap> List(Li, l -> MinimalGenerators(l));
[ [ 2, 23 ], [ 4, 6, 19 ], [ 4, 10, 15 ], [ 4, 11, 14 ],
  [ 6, 8, 11 ] ]
```

## References
