---
title: "Duplication of a numerical semigroup"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @Prs, @JMDA
---

<!-- https://www.ugr.es/~imns2010/2014/Slides/IMNS_2014_Strazzanti.pdf -->

## Definition

Let $T$ and $S$ be [numerical semigroups](../Basic-concepts/Numerical-semigroup.qmd), $E$ a [proper ideal](../Ideals-NS/Proper-ideal.qmd) of $S$ and $b$ a positive odd integer. It is said that $T$ is a duplication of $S$ by $E$ and $b$ if $T = 2S \cup (2E + b)$, where for any subset $X$ of $\mathbb{Z}$, $2X$ denotes the set

$$
2X = \{2x ~ | ~ x \in X\}.
$$

The set $2S \cup (2E + b)$ is not always a numerical semigroup, but it can be proven that $E + E + b \subseteq S$ is a sufficient condition, where $E + E + b$ denotes the set

$$
E + E + b = \{e + e' + b ~ | ~ e, e' \in E\}.
$$

## Examples

$\circ$ Let $S = \langle 3, 8, 10 \rangle, ~ T = \langle 6, 13, 16, 20 \rangle$, $I = \{6\} + S$ and $b = 1$, let us prove that $T$ is a duplication of $S$ by $I$ and $b$. Computing the first elements of $T$, $2S$ and $2I + b$,

$$
T = \{0, 6, 12, 13, 16, 18, 19, 20, 22, 24, 25, 26, 28, \rightarrow\},
$$

$$
2S = 2 \cdot \{0, 3, 6, 8, \rightarrow \} = \{0, 6, 12\} \cup \{2x ~ | ~ x \ge 8\},
$$
$$
2I + b = 2 \cdot \{6,9,12,14, \rightarrow\} + 1 = \{13, 19, 25\} \cup \{2x + 1 ~ | ~ x \ge 14\},
$$
where it is deduced that $T = 2S \cup (2E + b)$.


## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 23, 82, 93, 94, 143 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(23, 82, 93, 94, 143);
<Numerical semigroup with 5 generators>
```

Given a numerical semigroup $S$, a proper ideal $I$, and an odd integer $b$, the function `NumericalDuplication` returns the duplication of $S$ by $I$ and $b$ if the condition $2I + b \subseteq S$ is satisfied.

``` gap
gap> I := [92, 138] + S;
<Ideal of numerical semigroup>
gap> IsIntegral(I);
true
gap> b := 13;
13
gap> D := NumericalDuplication(S, I, b);
<Numerical semigroup with 6 generators>
```

$\diamond$ Let $T = \langle 8, 12, 14, 27 \rangle$, in GAP:

``` gap
gap> T := NumericalSemigroup(8, 12, 14, 27);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $T$, the function `AsNumericalDuplication` returns a list $[S, E, b]$ if $T$ is a duplication of $S$ by $E$ and $b$ if this is possible, and `fail` otherwise

``` gap
gap> L := AsNumericalDuplication(T);
[ <Numerical semigroup with 3 generators>, <Ideal of numerical semigroup>,
  7 ]
gap> S := L[1];
<Numerical semigroup with 3 generators>
gap> MinimalGenerators(S);
[ 4, 6, 7 ]
gap> I := L[2];
<Ideal of numerical semigroup>
gap> MinimalGenerators(I);
[ 10 ]
gap> b := L[3];
7
```

Then, $T = 2S \cup (2I + b)$ where $S = \langle 4, 6, 7 \rangle, I = \{10\} + S$ and $b = 7$.

## References

::: {#refs}

:::
