---
title: "Homogeneous numerical semigroup"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @HNS, @JMDA
---

<!-- [JZA18] Jafari, R. and Zarzuela Armengou, S., Homogeneous numerical semigroups, Semigroup Forum, 97 (2) (2018), 278--306. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) with [multiplicity](../Basic-concepts/Multiplicity.qmd) $m$ and let $Ap(S,m)$ be the [Apéry set](../Basic-concepts/Apery-set.qmd) of $m$ in $S$. It is said that $S$ is homogeneous if for every element in $Ap(S, m)$, its [set of lengths](../Fact-and-div/Set-of-lengths.qmd) has one element, that is, all its [factorizations](../Presentations-NS/Set-of-factorizations.qmd) has the same [length](../Fact-and-div/Set-of-lengths.qmd).

From the definition, if $S$ has [Apéry set of unique expression](NS-Apery-set.qmd), then $S$ is homogeneous.

## Examples

$\circ$ Let $S = \langle 7, 12, 15 \rangle$. The multiplicity of $S$ is $m = 7$ and the Apéry set of $m$ in $S$ is

$$
Ap(S, 7) = \{0, 15, 30, 24, 39, 12, 27\}.
$$ The set of factorizations of each element in $Ap(S,7) \setminus \{0\}$ is

$$
\mathbf{Z}(15) = \{(0,0,1)\}, ~~ \mathbf{Z}(30) = \{(0,0, 2)\}, ~~ \mathbf{Z}(24) = \{(0,2,0)\},
$$

$$
\mathbf{Z}(39) = \{(0,2,1)\}, ~~ \mathbf{Z}(10) = \{(0,1,0)\}, ~~ \mathbf{Z}(12) = \{(0,1,0)\}, ~~ \mathbf{Z}(27) = \{(0,1,1)\}
$$

Since each element has a unique factorization, it is concluded that $S$ is homogeneous.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 10, 84, 89, 96, 112, 113, 131 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(10, 84, 89, 96, 112, 113, 131);
<Numerical semigroup with 7 generators>
```

Given a numerical semigroup $S$, the function `IsHomogeneousNumericalSemigroup` returns true if $S$ is homogeneous and false otherwise.

``` gap
gap> IsHomogeneousNumericalSemigroup(S);
true
```

## References

::: {#refs}

:::
