---
title: "Numerical semigroup with maximal embedding dimension"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd), $e(S)$ the [embedding dimension](../Basic-concepts/Embedding-dimension.qmd) and $m(S)$ the [multiplicity](../Basic-concepts/Multiplicity.qmd) of $S$. Then, it is said that $S$ has maximal embedding dimension (or MED) if $e(S) = m(S)$.

It is well known that for every numerical semigroup, it holds the inequality $e(S) \le m(S)$.

## Examples

$\circ$ Let $S = \langle 3, 8 \rangle$. Clearly, $m(S) = 3$ and $e(S) = 2$, thus $S$ does not have maximal embedding dimension.

$\circ$ Let us consider $a,b \in \mathbb{N}$ with $gcd(a,b) = 1$ and $S = \langle a, a+1, a+2, \ldots, a+b \rangle$. By construction of $S$, $m(S) = a$. To compute $e(S)$, we divide into cases:

-   If $b \ge a-1$, then $B = \{a, a+1, \ldots, 2a - 1\}$ is the [minimal set of generators](../Basic-concepts/Minimal-set-of-generators.qmd) of $S$ and $e(S) = a$. Therefore $S$ has maximal embedding dimension.

-   If $b < a-1$, then $B = \{a, a+1, \ldots, a+b\}$ is the minimal set of generators of $S$, $e(S) = b+1$ and $S$ does not have maximal embedding dimension.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 4, 15, 20, 21, 22, 30, 31, 38 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(4, 15, 20, 21, 22, 30, 31, 38);
<Numerical semigroup with 8 generators>
```

Given a numerical semigroup $S$, the functions `IsMED` and `IsMEDNumericalSemigroup` return true if $S$ is MED (maximal embedding dimension) and false otherwise.

``` gap
gap> IsMED(S);
true
gap> IsMEDNumericalSemigroup(S);
true
```

Therefore, $e(S) = m(S)$. Given a numerical semigroup $S$, the functions `EmbeddingDimension` and `Multiplicity` computes the embedding dimension and the multiplicity of $S$.

``` gap
gap> Multiplicity(S);
4
gap> EmbeddingDimension(S);
4
```

## References
