---
title: "Saturated numerical semigroup"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is said that $S$ is saturated if for all $s, s_1, \ldots, s_r \in S$ such that $s_i \le s$ for all $i \in \{1, 2, \ldots, r\}$ and for all $z_1, \ldots, z_r \in \mathbb{Z}$ so that $z_1 s_1 + \cdots + z_r s_r \ge 0$, it holds $s + z_1 s_1 + \cdots + z_r s_r \in S$.

## Examples

$\circ$ Let $S = \langle 7, 11, 15, 16, 17, 19, 20 \rangle$ and let $s = s_1 = 11$ and $s_2 = 7$. For $z_1 = 2, z_2 = -3$, we have $z_1 s_1 + z_2 s_2 = 2 \cdot 11 - 3 \cdot 7 = 1 \ge 0$, but $11 + 1 = 12 \not \in S$. Therefore, $S$ is not saturated. It can be proven that $S$ is [Arf](Arf-semigroup.qmd).

$\circ$ Every saturated numerical semigroup $S$ is Arf. Indeed, given $x \ge y \ge z$, we have $y - z \ge 0$. Since $S$ is saturated, $x + y - z \in S$ and $S$ is Arf.

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 14, 17, 46, 49 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(14, 17, 46, 49);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$, the function `IsSaturated` returns true or false depending on whether the numerical semigroup is saturated or not.

``` gap
gap> IsSaturated(S);
false
```

$\diamond$ Given an integer $f$, the function `SaturatedNumericalSemigroupsWithFrobeniusNumber` returns a list with all the saturated numerical semigroups with Frobenius number $f$.

``` gap
gap> Length(SaturatedNumericalSemigroupsWithFrobeniusNumber(23));
84
```

## References
