---
title: "Frobenius variety"
format: html
engine: markdown
---

<!-- Definición de Num. Sem. -->

## Definition

Let $V$ be a non-empty set of [numerical semigroups](../Basic-concepts/Numerical-semigroup.qmd). It is said that $V$ is a Frobenius variety if fulfill the following conditions:

1)  If $S, T \in V$, then $S \cap T \in V$,

2)  If $S \in V$ and $S \ne \mathbb{N}$, then $S \cup \{F(S)\} \in V$,

where $F(S)$ denotes the [Frobenius number](../Basic-concepts/Frobenius-number.qmd) of $S$. It is well known that the intersection of two numerical semigroups is also a numerical semigroup and for any numerical semigroup $S$, the set $S \cup \{F(S)\}$ is also a numerical semigroup. Therefore, the conditions of Frobenius variety are well defined.

## Examples

$\circ$ Let $A$ be a subset of $\mathbb{N}$, $\mathcal{S}$ the set of numerical semigroups and let us consider the set $V = \{S \in \mathcal{S} ~ | ~ A \subseteq S \}$. $V$ is a Frobenius variety:

-   If $S,T \in V$, by definition $A \subseteq S$ and $A \subseteq T$, then $A \subseteq S \cap T$ and $S \cap T \in V$.

-   If $S \in V$, we have $A \subseteq S \subsetneq S \cup \{F(S)\}$, Therefore, $S \cup \{F(S)\} \in V$.

## References
