---
title: "Pattern"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ns, @JMDA
---

<!-- Definición de Num. Sem. -->

## Definition

It is said that an expression $P$ is a pattern if it is of the form $a_1x_1 + \cdots + a_nx_n$ with $x_1, \ldots, x_n$ unknowns and $a_1, \ldots, a_n$ nonzero integers. If a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) $S$ holds that for every $s_1, \ldots, s_n \in S$ with $s_1 \ge s_2 \ge \ldots \ge s_n$, the element $a_1s_1 + \cdots + a_n s_n$ belongs to $S$, it is said that $S$ is a [numerical semigroup admitting the pattern](../Families-NS/NS-admitting-pattern.qmd). It is denoted by $\mathcal{S}(P)$ the set of all numerical semigroups admitting the pattern $P$.

It is said that a pattern $P$ is admissible if $\mathcal{S}(P)$ is not empty. If the pattern defined by

$$
P' = \begin{cases} 
(a_1-1)x_1 + a_2 x_2 + \cdots + a_n x_n & \text{ if } a_1 > 1, \\
a_2 x_2 + \cdots + a_n x_n & \text{ otherwise, }
\end{cases}
$$ is also admissible, it is said that $P$ is strongly admissible.

## Examples

$\circ$ Let $P \equiv x_1 + x_2 - x_3$. It holds $\mathbb{N} \in \mathcal{S}(P)$, since for all $m_1 \ge m_2 \ge m_3$,

$$
m_1 + m_2 - m_3 = m_1 + (m_2 - m_3) \ge 0.
$$

Hence, $P$ is admissible. On the other hand, $P' = x_2 - x_3$, which is also admissible. Therefore, $P$ is strongly admissible. The set $\mathcal{S}(x_1 + x_2 - x_3)$ is the set of [Arf semigroups](../Families-NS/Arf-semigroup.qmd).

## Examples with GAP

The following examples are made with the package NumericalSgps in GAP.

$\diamond$ Given a list of non-negative integers, the function `IsAdmissiblePattern` returns true or false depending on whether the pattern $P$ defined by the list is admissible or not.

``` gap
gap> IsAdmissiblePattern([6, -4, -2]);
true
```

That means, there exists a numerical semigroup $S$ such that admits the pattern $P \equiv 6x - 4x - 2x$.

$\diamond$ Given a list of non-negative integers, the function `IsStronglyAdmissiblePattern` returns true or false depending on whether the pattern $P$ defined by the list is strongly admissible or not.

``` gap
gap> IsAdmissiblePattern([7, -2, -5]);
true
gap> IsStronglyAdmissiblePattern([7, -2, -5]);
false
```

That means, the set $\mathcal{S}(P)$ is non-empty but the set $\mathcal{S}(P')$ it is.

## References

::: {#refs}

:::

