---
title: "V-monoid generated by a subset"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ns
---

<!-- Sem. Num. -->

## Definition

The definition of $\mathcal{V}-$system of generators comes from the following result.

::: {.callout-note appearance="minimal"}
$\textbf{Proposition}$: The intersection of [V-monoids](V-monoid.qmd) is a $\mathcal{V}-$monoid.
:::


Let $\mathcal{V}$ be a [Frobenius variety](Frobenius-variety.qmd) and let $X$ be a subset of $\mathbb{N}$. It is defined the $\mathcal{V}-$monoid generated by $X$, denoted by $\mathcal{V}(X)$, as the intersection of all $\mathcal{V}-$monoids that contains $X$. The subset $X$ is called a $\mathcal{V}-$system of generators of $\mathcal{V}(X)$ and it is called minimal if no proper subset of $X$ is a $\mathcal{V}-$system of generators.

From the definition, $\mathcal{V}(X)$ is the smallest $\mathcal{V}-$monoid that contains $X$. It can be proven that every $\mathcal{V}-$monoid has a unique minimal $\mathcal{V}-$system of generators.



## Examples

$\circ$ Let $X = \langle 4, 6, 7 \rangle$ and $\mathcal{V}$ the family of [Arf numerical semigroups](../Families-NS/Arf-semigroup.qmd), which is a Frobenius Variety. Since $X$ is a numerical semigroup, if $X \subseteq M$ with $M$ a $\mathcal{V}-$monoid, then $M$ is a numerical semigroup. Therefore, $\mathcal{V}(X)$ is the [Arf closure](../Basic-concepts/Arf-closure.qmd) of $X$, which is $S = \langle 4, 6, 7 \rangle$. It can be proven that $A = \{4,6,7\}$ is the minimal $\mathcal{V}-$system of generators of $S$ (see [Arf system of generators](../Basic-concepts/Arf-system-of-generators.qmd)).



## References

::: {#refs}

:::

