---
title: "V-monoid"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @ns
---

<!-- Definición de Num. Sem. -->

## Definition

Let $\mathcal{V}$ be a [Frobenius variety](Frobenius-variety.qmd). It is said that a submonoid $M$ of $\mathbb{N}$ is a $\mathcal{V}-$monoid if it can be expressed as the intersection of elements of $\mathcal{V}$.

It is deduced from the definition that the intersection of $\mathcal{V}-$monoids is a $\mathcal{V}-$monoid.


## Examples


$\circ$ Let $\mathcal{V}$ be the set of all numerical semigroups. It is well known that $\mathcal{V}$ is a Frobenius variety. Then, the $\mathcal{V}-$monoids correspond to the elements of $\mathcal{V}$ and the monoids generated by no finite intersections of numerical semigroups. For example, if we consider for each $i \in \mathbb{N} \setminus \{0\}$ the [half-line](../Families-NS/NS-half-line.qmd) $S_i = \{0, i, \rightarrow\}$, it holds that

$$
\bigcap_{i = 1}^{+ \infty} S_i = \{0\},
$$
is a $\mathcal{V}-$monoid, but $\{0\}$ is not an element of $\mathcal{V}$.


## References

::: {#refs}

:::



