---
title: "Presentation of a numerical semigroup"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd), let $\phi$ be the [factorization homomorphism](Factorization-homomorphism.qmd) of $S$ and let $\ker(\phi)$ be the kernel of $\phi$ as a [congruence](Congruence-set.qmd). A set $\rho \subseteq \ker(\phi)$ is a presentation of $S$ if $\rho$ is a generator system of $\ker(\phi)$, that is, if $\ker(\phi) = Cong(\rho)$. It is said that $\rho$ is a minimal presentation if no proper subsets of $\rho$ is a presentation.

If $\rho$ is a minimal presentation, its elements are called minimal relators. Since there is not generally an unique minimal presentation, there may be minimal relators which do not belong in a particular minimal presentation.

## Examples

$\circ$ Let us consider $a,b \in \mathbb{N} \setminus \{0,1\}$ with $gcd(a,b) = 1$ and $S = \langle a, b \rangle$. Let us prove that $\{[(b,0), (0,a)]\}$ is a minimal presentation of $S$. Given $[(\alpha_1, \beta_1), (\alpha_2, \beta_2)] \in \ker(\phi)$, and with loss of generality let us suppose $\alpha_1 > \alpha_2$, we have

$$
\alpha_1a + \beta_1b = \phi(\alpha_1, \beta_1) = \phi(\alpha_2, \beta_2) = \alpha_2a + \beta_2 b,
$$

or equivalently,

$$
(\alpha_1 - \alpha_2)a = (\beta_2 - \beta_1)b.
$$

From this equality, since $gcd(a,b) = 1$, it is deduced that exists $q \in \mathbb{N}$ such that $\alpha_1 = \alpha_2 + bq$ and $\beta_2 = \beta_1 + aq$. If $q = 0$ it is clear. Otherwise,

$$
[(\alpha_1, \beta_1), (\alpha_2, \beta_2)] = [(\alpha_2, \beta_1), (\alpha_2, \beta_1)] + q[(b,0), (0,a)].
$$

$$
= [(b,0), (0,a)] + (q-1)[(b,0), (0,a)] + [(\alpha_2, \beta_1), (\alpha_2, \beta_1)].
$$

Therefore, $[(\alpha_1, \beta_1), (\alpha_2, \beta_2)] \in Cong([(b, 0), (0, a)])$. Finally, is a minimal presentation since it only has one element.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 7, 15, 20, 31, 39 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(7, 15, 20, 31, 39);
<Numerical semigroup with 3 generators>
```

In order to compute the minimal presentation of $S$, the function `MinimalPresentation` returns a list with the minimal generators of the kernel of $\phi$.

``` gap
gap> MinimalPresentation(S);
[ [ [ 0, 0, 0, 0, 2 ], [ 1, 0, 2, 1, 0 ] ], [ [ 0, 0, 0, 1, 1 ], [ 0, 2, 2, 0, 0 ] ],
  [ [ 0, 0, 0, 2, 0 ], [ 1, 1, 2, 0, 0 ] ], [ [ 0, 0, 1, 0, 1 ], [ 2, 3, 0, 0, 0 ] ],
  [ [ 0, 0, 1, 1, 0 ], [ 3, 2, 0, 0, 0 ] ], [ [ 0, 0, 3, 0, 0 ], [ 0, 4, 0, 0, 0 ] ],
  [ [ 0, 1, 0, 0, 1 ], [ 2, 0, 2, 0, 0 ] ], [ [ 0, 1, 0, 1, 0 ], [ 1, 0, 0, 0, 1 ] ],
  [ [ 0, 1, 1, 0, 0 ], [ 5, 0, 0, 0, 0 ] ], [ [ 0, 3, 0, 0, 0 ], [ 2, 0, 0, 1, 0 ] ] ]
```

This minimal presentation says that $S$ is a commutative monoid generated by three elements, $a,b,c,d, e$ under the above relations.

If we want all the minimal relators in a numerical semigroup, the function `AllMinimalRelationsOfNumericalSemigroup` computes it.

``` gap
gap> AllMinimalRelationsOfNumericalSemigroup(S);
[ [ [ 0, 2, 2, 0, 0 ], [ 0, 0, 0, 1, 1 ] ], [ [ 0, 4, 0, 0, 0 ], [ 0, 0, 3, 0, 0 ] ],
  [ [ 1, 0, 0, 0, 1 ], [ 0, 1, 0, 1, 0 ] ], [ [ 1, 0, 2, 1, 0 ], [ 0, 0, 0, 0, 2 ] ],
  [ [ 1, 1, 2, 0, 0 ], [ 0, 0, 0, 2, 0 ] ], [ [ 2, 0, 0, 1, 0 ], [ 0, 3, 0, 0, 0 ] ],
  [ [ 2, 0, 2, 0, 0 ], [ 0, 1, 0, 0, 1 ] ], [ [ 2, 1, 0, 1, 0 ], [ 0, 0, 3, 0, 0 ] ],
  [ [ 2, 3, 0, 0, 0 ], [ 0, 0, 1, 0, 1 ] ], [ [ 3, 0, 0, 0, 1 ], [ 0, 0, 3, 0, 0 ] ],
  [ [ 3, 2, 0, 0, 0 ], [ 0, 0, 1, 1, 0 ] ], [ [ 4, 0, 0, 1, 0 ], [ 0, 0, 1, 0, 1 ] ],
  [ [ 4, 2, 1, 0, 0 ], [ 0, 0, 0, 0, 2 ] ], [ [ 5, 0, 0, 0, 0 ], [ 0, 1, 1, 0, 0 ] ],
  [ [ 5, 1, 1, 0, 0 ], [ 0, 0, 0, 1, 1 ] ], [ [ 6, 0, 1, 0, 0 ], [ 0, 0, 0, 2, 0 ] ],
  [ [ 9, 1, 0, 0, 0 ], [ 0, 0, 0, 0, 2 ] ], [ [ 10, 0, 0, 0, 0 ], [ 0, 0, 0, 1, 1 ] ]
 ]
```

On the other hand, the function `IsMinimalRelationOfNumericalSemigroup` returns true or false depending on whether a pair (a relation) is a minimal relator or not.

``` gap
gap> IsMinimalRelationOfNumericalSemigroup([ [0, 1, 0, 0, 1], [2, 0, 2, 0, 0] ], S);
true
gap> IsMinimalRelationOfNumericalSemigroup([ [4, 0, 0, 5, 1], [12, 4, 0, 0, 2] ], S);
false
```

## References
