---
title: "Shaded set"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $A = \{n_1, n_2, \ldots, n_p\}$ a [minimal system of generators](../Basic-concepts/Minimal-set-of-generators.qmd) of $S$. Let $n \in S$, it is defined the shaded set of $n$ in $S$ as

$$
\mathcal{F}(n) = \left \{ V \subseteq A ~ | ~ n - \sum_{a \in V} a \in S \right \}.
$$

It can be proven that $A \in \mathcal{F}(n)$ if, and only if, $\mathcal{F}(n) = \mathcal{P}(A)$, where $\mathcal{P}(A)$ denotes the partition set of $A$.

## Examples

$\circ$ Let $S = \langle 5, 9, 13 \rangle$ and $n = 35 \in S$. In order to compute the shaded set of $n$ in $S$, we divide in cases:

-   $V \subseteq A$ has $0$ elements: we have $V = \emptyset$ and $V \in \mathcal{F}(35)$.

-   $V \subseteq A$ has $1$ element: the candidates are $T_{1,1} = \{5\}, T_{1,2} = \{9\}$ and $T_{1,3} = \{13\}$. Since $35 - 5 = 30, 35 - 9 = 26, 35 - 13 = 22$ and $\{30, 26, 22\} \subseteq S$, it is obtained that $T_{1,1}, T_{1,2}, T_{1,3} \in \mathcal{F}(35)$.

-   $V \subseteq A$ has $2$ element: the candidates are $T_{2,1} = \{5,9\}, T_{2,2} = \{5, 13\}$ and $T_{2,3} = \{9, 13\}$, but $T_{2,3}$ is the only one that satisfies the condition, thus $T_{2,3} \in \mathcal{F}(35)$ and $T_{2,1}, T_{2,2} \not \in \mathcal{F}(35)$.

-   $V \subseteq A$ has $3$ element: we have $V = A$ and $35 - (5 + 9 + 13) = 8 \not \in S$, then $A \not \in \mathcal{F}(35)$.

To sum up, the shaded set of $n = 35$ in $S$ is

$$
\mathcal{F}(35) = \{\emptyset, \{5\}, \{9\}, \{13\}, \{9, 13\}\}.
$$

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 15, 20, 27, 31, 32 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(15, 20, 27, 31, 32);
<Numerical semigroup with 5 generators>
```

Given a numerical semigroup $S$ and an element $n$ of it, the function `ShadedSetOfElementInNumericalSemigroup` returns the shaded set of $n$ in $S$.

``` gap
gap> ShadedSetOfElementInNumericalSemigroup(85,S);
[ [  ], [ 15 ], [ 15, 20 ], [ 20 ], [ 27 ], [ 27, 31 ], [ 31 ] ]
```

It may be $n, m \in S$ such that $\mathcal{F}(n) = \mathcal{F}(m)$ but $n \ne m$.

``` gap
gap> ShadedSetOfElementInNumericalSemigroup(70,S);
[ [  ], [ 15 ], [ 15, 20 ], [ 20 ] ]
gap> ShadedSetOfElementInNumericalSemigroup(75,S);
[ [  ], [ 15 ], [ 15, 20 ], [ 20 ] ]
gap> ShadedSetOfElementInNumericalSemigroup(80,S);
[ [  ], [ 15 ], [ 15, 20 ], [ 20 ] ]
```

## References
