---
title: "Adjacent catenary degree of an element"
format: html
engine: markdown
---

<!-- -->

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd), $s \in S$ and $\mathbf{Z}(s)$ its [set of factorizations](../Presentations-NS/Set-of-factorizations.qmd). Let us consider $l_1, \ldots, l_t$ the [lengths](Length-factorization.qmd) of the factorizations of $s$ in $S$ and $\mathbf{Z}_{l_i}$ the set of factorizations of $s$ with length $l_i$. It is defined the adjacent catenary degree of $s$ in $S$, denoted by $AdjC(s)$, as

$$
AdjC(s) = \max \{d(\mathbf{Z}_{l_i}, \mathbf{Z}_{l_{i+1}}) ~ | ~ i \in \{1, \ldots, n-1\}  \},
$$

where $d(\mathbf{Z}_{l_i}, \mathbf{Z}_{l_{i+1}})$ is defined as

$$
d(\mathbf{Z}_{l_i}, \mathbf{Z}_{l_{i+1}}) = \min \{d(x,y) ~ | ~ x \in \mathbf{Z}_{l_i}, ~ y \in \mathbf{Z}_{l_{i+1}}\},
$$ 

with $d(x,y)$ denoting the [distance](Distance-factorizations.qmd) between $x$ and $y$.

## Examples

$\circ$ Let $S = \langle 7, 12, 15 \rangle$ and $s = 100$. If $(\alpha, \beta, \gamma) \in \mathbf{Z}(100)$, then

$$
7 \cdot \alpha + 12 \cdot \beta + 15 \cdot \gamma = 100,
$$ 

where necessarily $0 \le \alpha \le 7, ~ 0 \le \beta \le 8, ~ 0 \le \gamma \le 6$, deducing that

$$
\mathbf{Z}(100) = \{(4, 6, 0), (7, 3, 1), (10, 0, 2), (1, 4, 3), (4, 1, 4) \}.
$$ 

Their lengths are $(l_1, \ldots, l_5) = (8,9,10,11,12)$ and

$$
\mathbf{Z}_8 = \{(1,4,3)\}, ~~ \mathbf{Z}_9 = \{(4,1,4)\}, ~~ \mathbf{Z}_{10} = \{(4,6,0)\}, ~~ \mathbf{Z}_{11} = \{(7,3,1)\}, ~~ \mathbf{Z}_{12} = \{(10, 0, 2)\}.
$$ 

Finally,

$$
d(\mathbf{Z}_8, \mathbf{Z}_9) = d((1,4,3), (4,1,4)) = 4, ~~ d(\mathbf{Z}_9, \mathbf{Z}_{10}) = d((4,1,4), (4,6,0)) = 5
$$ 

$$
d(\mathbf{Z}_{10}, \mathbf{Z}_{11}) = d((4,6,0), (7,3,1)) = 4, ~~ d(\mathbf{Z}_{11}, \mathbf{Z}_{12}) = d((7,3,1), (10, 0, 2)) = 4,
$$ 

concluding that $AdjC(100) = 5$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 13, 14, 33, 64, 76 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(13, 14, 33, 64, 76);
<Numerical semigroup with 5 generators>
```

Given a set of factorizations $Is$, the function `AdjacentCatenaryDegreeOfSetOfFactorizations` returns the adjacent catenary degree of $Is$. Given a numerical semigroup $S$ and an element $n \in S$, the function `Factorizations` returns the set of factorizations of $n$ in $S$.

``` gap
gap> 300 in S;
true
gap> Is := Factorizations(S, 300);
[ [ 22, 1, 0, 0, 0 ], [ 8, 14, 0, 0, 0 ], [ 13, 7, 1, 0, 0 ], [ 18, 0, 2, 0, 0 ],
  [ 4, 13, 2, 0, 0 ], [ 9, 6, 3, 0, 0 ], [ 0, 12, 4, 0, 0 ], [ 5, 5, 5, 0, 0 ],
  [ 1, 4, 7, 0, 0 ], [ 16, 2, 0, 1, 0 ], [ 2, 15, 0, 1, 0 ], [ 7, 8, 1, 1, 0 ],
  [ 12, 1, 2, 1, 0 ], [ 3, 7, 3, 1, 0 ], [ 8, 0, 4, 1, 0 ], [ 10, 3, 0, 2, 0 ],
  [ 1, 9, 1, 2, 0 ], [ 6, 2, 2, 2, 0 ], [ 2, 1, 4, 2, 0 ], [ 4, 4, 0, 3, 0 ],
  [ 0, 3, 2, 3, 0 ], [ 14, 3, 0, 0, 1 ], [ 0, 16, 0, 0, 1 ], [ 5, 9, 1, 0, 1 ],
  [ 10, 2, 2, 0, 1 ], [ 1, 8, 3, 0, 1 ], [ 6, 1, 4, 0, 1 ], [ 2, 0, 6, 0, 1 ],
  [ 8, 4, 0, 1, 1 ], [ 4, 3, 2, 1, 1 ], [ 0, 2, 4, 1, 1 ], [ 2, 5, 0, 2, 1 ],
  [ 6, 5, 0, 0, 2 ], [ 2, 4, 2, 0, 2 ], [ 0, 6, 0, 1, 2 ], [ 3, 0, 1, 0, 3 ] ]
gap> AdjacentCatenaryDegreeOfSetOfFactorizations(Is);
14
```

## References
