---
title: "Apéry set of an integer"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $x \in \mathbb{N} \setminus \{0\}$. It is defined the Apéry set of $x$ in $S$, denoted by $Ap(S,x)$, as

$$
Ap(S,x) = \{s \in S ~ | ~ s - x \not \in S \}.
$$

This definition generalizes the definition of [Apéry set](../Basic-concepts/Apery-set.qmd) of $s \in S \setminus \{0\}$ in $S$.

## Examples

$\circ$ Let $S = \langle 3, 8, 13 \rangle = \{0, 3, 6, 8, 9, 11, \rightarrow\}$ and $x = 2 \not \in S$. The [conductor](../Basic-concepts/Conductor.qmd) of $S$ is $C(S) = 11$, then if $s \ge C(S) + 2 = 13$, it holds $s - 2 \ge C(S)$ and $s-2 \in S$. Therefore, $Ap(S,2) \subseteq \{0, 3, 6, 8, 9, 11, 12\}$. It is obtained that $Ap(S,2) = \{0, 3, 6, 9, 12\}$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 9, 14, 29, 44 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(9, 14, 29, 44);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$ and an integer $x \in \mathbb{N} \setminus \{0\}$, the functions `AperyList` and `AperyListOfNumericalSemigroupWRTInteger` return the Apéry set of $x$ in $S$.

``` gap
gap> 15 in S;
false
gap> AperyList(S, 15);
[ 0, 9, 14, 18, 23, 27, 28, 32, 36, 37, 41, 45, 46, 50, 54, 55, 63, 64 ]
gap> AperyList(S, 15) = AperyListOfNumericalSemigroupWRTInteger(S, 15);
true
```

## References

::: {#refs}

:::
