---
title: "Desert of a numerical semigroup"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $G(S)$ the set of [gaps](../Basic-concepts/Gap.qmd) of $S$. A subset $A \subseteq \mathbb{Z}$ is a desert of $S$ if $A = \mathbb{Z}^{< 0}$ or $A \subseteq G(S)$ and $\min A - 1, \max A + 1 \in S$. Equivalently, $A$ is a desert of $S$ if $A$ is a maximal interval of gaps of $S$ (counting also the set of all negative integers).

It can be proven that the number of deserts is $|Ap(S, 1)|$, where $Ap(S,1)$ denotes the [Apéry set of the integer](Apery-set-integer.qmd) $1$.

## Examples

$\circ$ Let $S = \langle 4, 7, 10 \rangle = \{ 0, 4, 7, 8, 10, 11, 12, 14, \rightarrow \}$. The deserts of $S$ are

$$
A_0 = \mathbb{Z}^{<0}, A_1 = \{1, 2, 3\}, A_2 = \{5, 6\}, A_3 = \{9\}, A_4 = \{13\}.
$$

On the other hand,

$$
Ap(S,1) = \{0, 4, 7, 10, 14\}.
$$

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 21, 35, 43, 45, 79 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(21, 35, 43, 45, 79);
<Numerical semigroup with 5 generators>
```

Given a numerical semigroup $S$, the functions `Deserts` and `DesertsOfNumericalSemigroup` return a list with all the deserts of $S$, not counting the desert formed by the all negative integers.

``` gap
gap> Deserts(S);
[ [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ],
  [ 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 ], [ 36, 37, 38, 39, 40, 41 ],
  [ 44 ], [ 46, 47, 48, 49, 50, 51, 52, 53, 54, 55 ], [ 57, 58, 59, 60, 61, 62 ],
  [ 65 ], [ 67, 68, 69 ], [ 71, 72, 73, 74, 75, 76 ], [ 81, 82, 83 ], [ 89 ],
  [ 92, 93, 94, 95, 96, 97 ], [ 102, 103, 104 ], [ 110 ], [ 116, 117, 118 ],
  [ 137, 138, 139 ] ]
gap> Length(Deserts(S)) + 1;
17
```

On the other hand, given a numerical semigroup $S$ and an integer $x \in \mathbb{N} \setminus \{0\}$, the function `AperyList` returns the Apéry set of $x$ in $S$.

``` gap
gap> AperyList(S, 1);
[ 0, 21, 35, 42, 45, 56, 63, 66, 70, 77, 84, 90, 98, 105, 111, 119, 140 ]
gap> Length(AperyList(S,1));
17
```

## References

::: {#refs}

:::
