---
title: "Elasticity of an element"
format: html
engine: markdown
bibliography: ../Bibliography.bib
cls: apa
---

---
nocite: |
  @nsapp2, @JMDA
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) and $s \in S$. If $\mathbf{L}(s)$ denotes the [set of lengths](Set-of-lengths.qmd) of $s$, it is defined the elasticity of $s$, denoted by $\rho(s)$, as

$$
\rho(s) = \frac{\max \mathbf{L}(s)}{\min \mathbf{L}(s)}.
$$

From the elasticity of an element it is defined the [elasticity of a numerical semigroup](Elasticity-NS.qmd).

## Examples

$\circ$ Let $S = \langle 5, 9, 16 \rangle$, $s = 56 \in S$ and $\mathbf{Z}(s)$ the [set of factorizations](../Presentations-NS/Set-of-factorizations.qmd) of $s$ in $S$. If $(\alpha, \beta, \gamma) \in \mathbf{Z}(s)$, then $0 \le \alpha \le 11, 0 \le \beta \le 6, 0 \le \gamma \le 3$, from which it follows that $\mathbf{Z}(56) = \{(4,4,0), (8,0,1), (3,1,2)\}$. Its set of lengths is $\mathbf{L}(56) = \{6, 8, 9\}$ and the elasticity of $s = 56$ is $\rho(56) = 3/2$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 14, 31, 68, 81 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(14, 31, 68, 81);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$ and an element $n \in S$, the functions `Elasticity` and `ElasticityOfFactorizationsElementWRTNumericalSemigroup` return the elasticity of $n$ in $S$. Given only a numerical semigroup $S$, this function returns the elasticity of $S$.

``` gap
gap> Elasticity(250, S);
2
gap> Elasticity(S, 250);
2
gap> Elasticity(250, S) = ElasticityOfFactorizationsElementWRTNumericalSemigroup(250, S);
true
gap> Elasticity(S);
81/14
```

The function `LengthsOfFactorizationsElementWRTNumericalSemigroup` returns the set of lengths of an element of a numerical semigroup.

``` gap
gap> LengthsOfFactorizationsElementWRTNumericalSemigroup(250, S);
[ 7, 8, 13, 14 ]
```

## References

::: {#refs}

:::