---
title: "Equal catenary degree of a numerical semigroup"
format: html
engine: markdown
---

```{=html}
<!-- //// P. A. García-Sánchez, I. Ojeda, A.
Sánchez-R.-Navarro, Factorization invariants in half-factorial affine
semigroups, Internat. J. Algebra Comput. 23 (2013), 111–122. -->
```
## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd). It is defined the equal catenary degree of $S$, denoted by $EqC(S)$, as

$$
EqC(S) = \max_{s \in S} EqC(s),
$$

where $EqC(s)$ denotes the [equal catenary degree](Equal-catenary-degree-element.qmd) of $s$ in $S$.

It can be proven that $EqC(S) = \max_{s \in I} EqC(s)$, where $I$ is the set of [degrees of primitive elements](../Basic-concepts/Degree-of-a-primitive-element.qmd) of $S$.

## Examples

Let $S = \langle 4, 6, 11 \rangle$. The primitive elements of $S$ are the minimal solutions of the equation

$$
4(x_1 - y_1) + 6(x_2 - y_2) + 11(x_3 - y_3) = 0.
$$

Applying elimination theorem and extension theorem from ring theory in several indeterminate, it is obtained that

$$
M = \langle (1,0,0,1,0,0), (0,1,0,0,1,0), (0, 0, 2, 1, 3, 0), (0, 0, 2, 4, 1, 0),
  (0, 0, 4, 11, 0, 0), (0, 0, 6, 0, 11, 0), \\
$$

$$ 
(0, 1, 2, 7, 0, 0), (0, 2, 0, 3, 0, 0), (0, 5, 0, 2, 0, 2), (0, 8, 0, 1, 0, 4), (0,0,1,0,0,1) \rangle,
$$

and the degree of primitive elements of $S$ is $B =\{4, 6, 11, 12, 22, 28, 30, 44, 48, 66\}$, and $Eq(S) = \max_{s \in B} ~ Eq(s)$. Computing the [set of factorizations](../Presentations-NS/Set-of-factorizations.qmd) of each element in $B$, it is deduced that $Eq(S) = 7$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 3, 8, 10 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(3, 8, 10);
<Numerical semigroup with 3 generators>
```

Given a numerical semigroup $S$, the function `EqualCatenaryDegreeOfNumericalSemigroup` returns the equal catenary degree of $S$.

``` gap
gap> EqualCatenaryDegreeOfNumericalSemigroup(S);
7
```

## References
