---
title: "Generalized Feng-Rao distance of an element"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd), let $s \in S$ and $r \in \mathbb{N} \setminus \{0\}$. It is defined the generalized Feng-Rao distance of $s$ in $S$, denoted by $\delta_{FR}^r(s)$, as

$$
\delta_{FR}^r(s) = \{ |D(s_1, \ldots, s_r)| ~ : ~ s \le s_1 \le \cdots \le s_r \text{ and }  s_1, \ldots, s_r \in S\},
$$

where $D(s_1, \ldots, s_r) = \bigcup_{i = 1}^r D(s_i)$ and $D(s_i)$ denotes the [set of divisors](../Basic-concepts/Set-divisors.qmd) of $s_i \in S$. If $r = 1$, we have the [Feng-Rao distance](Feng-Rao-distance.qmd) of $s$ in $S$.

Given a numerical semigroup $S$ with [conductor](../Basic-concepts/Conductor.qmd) $C(S)$ and [genus](../Basic-concepts/Genus.qmd) $g(S)$, it can be proven that for all $m \ge 2C(S) - 1$,

$$
\delta_{FR}^2(m) = m + 1 - 2g(S) + \min \{|Ap(S, n)| ~~ : ~ n \in \mathbb{N} \setminus \{0\}\},
$$

where $Ap(S,n)$ is the [Apéry set of the integer](Apery-set-integer.qmd) $n$ in $S$.

## Examples

$\circ$ Let $S = \langle 3, 5, 7 \rangle = \{0, 3, 5, \rightarrow \}$. We have $C(S) = 5$ and $g(S) = 3$. On the other hand, we know that for all $n \in S$, it holds $|Ap(S,n)| = n$, then it is sufficient to compute the Apéry set for $n \in \{1, 2, 4\}$ and for $n = m(S) = 3$, where $m(S)$ denotes the [multiplicity](../Basic-concepts/Multiplicity.qmd) of $S$. It is obtained that

$$
Ap(S, 1) = \{0, 3, 5\}, ~~ Ap(S,2) = \{0, 3, 6\},
$$

$$
|Ap(S, m(S))| = m(S) = 3, ~~ Ap(S,4) = \{0, 3, 5, 8\}.
$$

Thus, if $m \ge 2C(S) - 1 = 9$,

$$
\delta_{FR}^2(m) = m + 1 - 2g(S) + 3 = m -2.
$$

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 14, 15, 20, 24 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(14, 15, 20, 24);
<Numerical semigroup with 4 generators>
```

Given a numerical semigroup $S$, an element $n \in S$ and $r \in \mathbb{N} \setminus \{0\}$, the function `FengRaoDistance` computes the $r$ generalized Feng-Rao distance of $n$ in $S$.

``` gap
gap> FengRaoDistance(S, 1, 62);
8
gap> FengRaoDistance(S, 2, 62);
12
gap> FengRaoDistance(S, 3, 62);
14
```

## References
