---
title: "w-primality of a numerical semigroup"
format: html
engine: markdown
---

## Definition

Let $S$ be a [numerical semigroup](../Basic-concepts/Numerical-semigroup.qmd) [minimally generated](../Basic-concepts/Minimal-set-of-generators.qmd) by $\{n_1, \ldots, n_p\}$. It is defined the $\omega-$primality of $S$, denoted by $\omega(S)$, as

$$
\omega(S) = \max \{ \omega(S, n_i) ~ | ~ i \in \{1, \ldots, p \}\,
$$ 

where $\omega(n_i)$ denotes the [w-primality](w-primality-of-an-element.qmd) of $n_i$ in $S$ for all $i \in \{1, \ldots, p\}$.

Given a numerical semigroup $S$, there is a relation between its [Delta set](Delta-set-of-a-numerical-semigroup.qmd) $\Delta(S)$, its [Catenary degree](Catenary-degree-of-a-numerical-semigroup.qmd) $\mathbf{C}(S)$, its $\omega-$primality $\omega(S)$ and its [tame degree](Tame-degree-of-a-numerical-semigroup.qmd) $\mathbf{t}(S)$, which is

$$
\max \Delta(S) + 2 \le \mathbf{C}(S) \le \omega(S) \le \mathbf{t}(S).
$$

## Examples

$\circ$ Let $S = \langle 10, 11, 17, 23 \rangle$. It is easy to check that its catenary degree is $\mathbf{C}(S) = 6$, then $\omega(S) \ge 6$. One can prove that also $\mathbf{t}(S) = 6$. Therefore, $\omega(S) = 6$.

## Examples with GAP

The following example is made with the package NumericalSgps in GAP.

$\diamond$ Let $S = \langle 22, 33, 45, 60, 75 \rangle$, in GAP:

``` gap
gap> S := NumericalSemigroup(22, 33, 45, 60, 75);
<Numerical semigroup with 5 generators>
```

Given a numerical semigroup $S$, the function `OmegaPrimality` returns the $\omega-$primality of $S$.

``` gap
gap> OmegaPrimality(S);
9
```

If we give also an element $n \in S$, then it computes the $\omega-$primality of $n$ in $S$.

``` gap
gap> OmegaPrimality(S, 207);
15
```

## References
